// Code generated by ent, DO NOT EDIT.

package videotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the videotask type in the database.
	Label = "video_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldDurationSeconds holds the string denoting the duration_seconds field in the database.
	FieldDurationSeconds = "duration_seconds"
	// FieldReferenceDurationSeconds holds the string denoting the reference_duration_seconds field in the database.
	FieldReferenceDurationSeconds = "reference_duration_seconds"
	// FieldBillableSeconds holds the string denoting the billable_seconds field in the database.
	FieldBillableSeconds = "billable_seconds"
	// FieldCostPerSecond holds the string denoting the cost_per_second field in the database.
	FieldCostPerSecond = "cost_per_second"
	// FieldTotalCost holds the string denoting the total_cost field in the database.
	FieldTotalCost = "total_cost"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldRequestJSON holds the string denoting the request_json field in the database.
	FieldRequestJSON = "request_json"
	// FieldUpstreamResponseJSON holds the string denoting the upstream_response_json field in the database.
	FieldUpstreamResponseJSON = "upstream_response_json"
	// FieldErrorJSON holds the string denoting the error_json field in the database.
	FieldErrorJSON = "error_json"
	// FieldResultVideoURL holds the string denoting the result_video_url field in the database.
	FieldResultVideoURL = "result_video_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldBilledAt holds the string denoting the billed_at field in the database.
	FieldBilledAt = "billed_at"
	// FieldRefundedAt holds the string denoting the refunded_at field in the database.
	FieldRefundedAt = "refunded_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAPIKey holds the string denoting the api_key edge name in mutations.
	EdgeAPIKey = "api_key"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the videotask in the database.
	Table = "video_tasks"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "video_tasks"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// APIKeyTable is the table that holds the api_key relation/edge.
	APIKeyTable = "video_tasks"
	// APIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	APIKeyInverseTable = "api_keys"
	// APIKeyColumn is the table column denoting the api_key relation/edge.
	APIKeyColumn = "api_key_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "video_tasks"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "video_tasks"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for videotask fields.
var Columns = []string{
	FieldID,
	FieldPublicID,
	FieldRequestID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldAccountID,
	FieldModel,
	FieldUpstreamModel,
	FieldResolution,
	FieldDurationSeconds,
	FieldReferenceDurationSeconds,
	FieldBillableSeconds,
	FieldCostPerSecond,
	FieldTotalCost,
	FieldActualCost,
	FieldStatus,
	FieldUpstreamTaskID,
	FieldRequestJSON,
	FieldUpstreamResponseJSON,
	FieldErrorJSON,
	FieldResultVideoURL,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCompletedAt,
	FieldBilledAt,
	FieldRefundedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PublicIDValidator is a validator for the "public_id" field. It is called by the builders before save.
	PublicIDValidator func(string) error
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// DefaultDurationSeconds holds the default value on creation for the "duration_seconds" field.
	DefaultDurationSeconds int
	// DefaultReferenceDurationSeconds holds the default value on creation for the "reference_duration_seconds" field.
	DefaultReferenceDurationSeconds int
	// DefaultBillableSeconds holds the default value on creation for the "billable_seconds" field.
	DefaultBillableSeconds int
	// DefaultCostPerSecond holds the default value on creation for the "cost_per_second" field.
	DefaultCostPerSecond float64
	// DefaultTotalCost holds the default value on creation for the "total_cost" field.
	DefaultTotalCost float64
	// DefaultActualCost holds the default value on creation for the "actual_cost" field.
	DefaultActualCost float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VideoTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByDurationSeconds orders the results by the duration_seconds field.
func ByDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSeconds, opts...).ToFunc()
}

// ByReferenceDurationSeconds orders the results by the reference_duration_seconds field.
func ByReferenceDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceDurationSeconds, opts...).ToFunc()
}

// ByBillableSeconds orders the results by the billable_seconds field.
func ByBillableSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillableSeconds, opts...).ToFunc()
}

// ByCostPerSecond orders the results by the cost_per_second field.
func ByCostPerSecond(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostPerSecond, opts...).ToFunc()
}

// ByTotalCost orders the results by the total_cost field.
func ByTotalCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCost, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByResultVideoURL orders the results by the result_video_url field.
func ByResultVideoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultVideoURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByBilledAt orders the results by the billed_at field.
func ByBilledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBilledAt, opts...).ToFunc()
}

// ByRefundedAt orders the results by the refunded_at field.
func ByRefundedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAPIKeyField orders the results by api_key field.
func ByAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
