// Code generated by ent, DO NOT EDIT.

package videotask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldPublicID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldRequestID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAccountID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldResolution, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldDurationSeconds, v))
}

// ReferenceDurationSeconds applies equality check predicate on the "reference_duration_seconds" field. It's identical to ReferenceDurationSecondsEQ.
func ReferenceDurationSeconds(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldReferenceDurationSeconds, v))
}

// BillableSeconds applies equality check predicate on the "billable_seconds" field. It's identical to BillableSecondsEQ.
func BillableSeconds(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldBillableSeconds, v))
}

// CostPerSecond applies equality check predicate on the "cost_per_second" field. It's identical to CostPerSecondEQ.
func CostPerSecond(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCostPerSecond, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldTotalCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldActualCost, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldStatus, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// ResultVideoURL applies equality check predicate on the "result_video_url" field. It's identical to ResultVideoURLEQ.
func ResultVideoURL(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldResultVideoURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCompletedAt, v))
}

// BilledAt applies equality check predicate on the "billed_at" field. It's identical to BilledAtEQ.
func BilledAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldBilledAt, v))
}

// RefundedAt applies equality check predicate on the "refunded_at" field. It's identical to RefundedAtEQ.
func RefundedAt(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldRefundedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldPublicID, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldGroupID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldAccountID, vs...))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldResolution, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldDurationSeconds, v))
}

// ReferenceDurationSecondsEQ applies the EQ predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldReferenceDurationSeconds, v))
}

// ReferenceDurationSecondsNEQ applies the NEQ predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsNEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldReferenceDurationSeconds, v))
}

// ReferenceDurationSecondsIn applies the In predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldReferenceDurationSeconds, vs...))
}

// ReferenceDurationSecondsNotIn applies the NotIn predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsNotIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldReferenceDurationSeconds, vs...))
}

// ReferenceDurationSecondsGT applies the GT predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsGT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldReferenceDurationSeconds, v))
}

// ReferenceDurationSecondsGTE applies the GTE predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsGTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldReferenceDurationSeconds, v))
}

// ReferenceDurationSecondsLT applies the LT predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsLT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldReferenceDurationSeconds, v))
}

// ReferenceDurationSecondsLTE applies the LTE predicate on the "reference_duration_seconds" field.
func ReferenceDurationSecondsLTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldReferenceDurationSeconds, v))
}

// BillableSecondsEQ applies the EQ predicate on the "billable_seconds" field.
func BillableSecondsEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldBillableSeconds, v))
}

// BillableSecondsNEQ applies the NEQ predicate on the "billable_seconds" field.
func BillableSecondsNEQ(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldBillableSeconds, v))
}

// BillableSecondsIn applies the In predicate on the "billable_seconds" field.
func BillableSecondsIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldBillableSeconds, vs...))
}

// BillableSecondsNotIn applies the NotIn predicate on the "billable_seconds" field.
func BillableSecondsNotIn(vs ...int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldBillableSeconds, vs...))
}

// BillableSecondsGT applies the GT predicate on the "billable_seconds" field.
func BillableSecondsGT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldBillableSeconds, v))
}

// BillableSecondsGTE applies the GTE predicate on the "billable_seconds" field.
func BillableSecondsGTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldBillableSeconds, v))
}

// BillableSecondsLT applies the LT predicate on the "billable_seconds" field.
func BillableSecondsLT(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldBillableSeconds, v))
}

// BillableSecondsLTE applies the LTE predicate on the "billable_seconds" field.
func BillableSecondsLTE(v int) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldBillableSeconds, v))
}

// CostPerSecondEQ applies the EQ predicate on the "cost_per_second" field.
func CostPerSecondEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCostPerSecond, v))
}

// CostPerSecondNEQ applies the NEQ predicate on the "cost_per_second" field.
func CostPerSecondNEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldCostPerSecond, v))
}

// CostPerSecondIn applies the In predicate on the "cost_per_second" field.
func CostPerSecondIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldCostPerSecond, vs...))
}

// CostPerSecondNotIn applies the NotIn predicate on the "cost_per_second" field.
func CostPerSecondNotIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldCostPerSecond, vs...))
}

// CostPerSecondGT applies the GT predicate on the "cost_per_second" field.
func CostPerSecondGT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldCostPerSecond, v))
}

// CostPerSecondGTE applies the GTE predicate on the "cost_per_second" field.
func CostPerSecondGTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldCostPerSecond, v))
}

// CostPerSecondLT applies the LT predicate on the "cost_per_second" field.
func CostPerSecondLT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldCostPerSecond, v))
}

// CostPerSecondLTE applies the LTE predicate on the "cost_per_second" field.
func CostPerSecondLTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldCostPerSecond, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldTotalCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldActualCost, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldStatus, v))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIsNil applies the IsNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDNotNil applies the NotNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// RequestJSONIsNil applies the IsNil predicate on the "request_json" field.
func RequestJSONIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldRequestJSON))
}

// RequestJSONNotNil applies the NotNil predicate on the "request_json" field.
func RequestJSONNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldRequestJSON))
}

// UpstreamResponseJSONIsNil applies the IsNil predicate on the "upstream_response_json" field.
func UpstreamResponseJSONIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldUpstreamResponseJSON))
}

// UpstreamResponseJSONNotNil applies the NotNil predicate on the "upstream_response_json" field.
func UpstreamResponseJSONNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldUpstreamResponseJSON))
}

// ErrorJSONIsNil applies the IsNil predicate on the "error_json" field.
func ErrorJSONIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldErrorJSON))
}

// ErrorJSONNotNil applies the NotNil predicate on the "error_json" field.
func ErrorJSONNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldErrorJSON))
}

// ResultVideoURLEQ applies the EQ predicate on the "result_video_url" field.
func ResultVideoURLEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldResultVideoURL, v))
}

// ResultVideoURLNEQ applies the NEQ predicate on the "result_video_url" field.
func ResultVideoURLNEQ(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldResultVideoURL, v))
}

// ResultVideoURLIn applies the In predicate on the "result_video_url" field.
func ResultVideoURLIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldResultVideoURL, vs...))
}

// ResultVideoURLNotIn applies the NotIn predicate on the "result_video_url" field.
func ResultVideoURLNotIn(vs ...string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldResultVideoURL, vs...))
}

// ResultVideoURLGT applies the GT predicate on the "result_video_url" field.
func ResultVideoURLGT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldResultVideoURL, v))
}

// ResultVideoURLGTE applies the GTE predicate on the "result_video_url" field.
func ResultVideoURLGTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldResultVideoURL, v))
}

// ResultVideoURLLT applies the LT predicate on the "result_video_url" field.
func ResultVideoURLLT(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldResultVideoURL, v))
}

// ResultVideoURLLTE applies the LTE predicate on the "result_video_url" field.
func ResultVideoURLLTE(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldResultVideoURL, v))
}

// ResultVideoURLContains applies the Contains predicate on the "result_video_url" field.
func ResultVideoURLContains(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContains(FieldResultVideoURL, v))
}

// ResultVideoURLHasPrefix applies the HasPrefix predicate on the "result_video_url" field.
func ResultVideoURLHasPrefix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasPrefix(FieldResultVideoURL, v))
}

// ResultVideoURLHasSuffix applies the HasSuffix predicate on the "result_video_url" field.
func ResultVideoURLHasSuffix(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldHasSuffix(FieldResultVideoURL, v))
}

// ResultVideoURLIsNil applies the IsNil predicate on the "result_video_url" field.
func ResultVideoURLIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldResultVideoURL))
}

// ResultVideoURLNotNil applies the NotNil predicate on the "result_video_url" field.
func ResultVideoURLNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldResultVideoURL))
}

// ResultVideoURLEqualFold applies the EqualFold predicate on the "result_video_url" field.
func ResultVideoURLEqualFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEqualFold(FieldResultVideoURL, v))
}

// ResultVideoURLContainsFold applies the ContainsFold predicate on the "result_video_url" field.
func ResultVideoURLContainsFold(v string) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldContainsFold(FieldResultVideoURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldCompletedAt))
}

// BilledAtEQ applies the EQ predicate on the "billed_at" field.
func BilledAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldBilledAt, v))
}

// BilledAtNEQ applies the NEQ predicate on the "billed_at" field.
func BilledAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldBilledAt, v))
}

// BilledAtIn applies the In predicate on the "billed_at" field.
func BilledAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldBilledAt, vs...))
}

// BilledAtNotIn applies the NotIn predicate on the "billed_at" field.
func BilledAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldBilledAt, vs...))
}

// BilledAtGT applies the GT predicate on the "billed_at" field.
func BilledAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldBilledAt, v))
}

// BilledAtGTE applies the GTE predicate on the "billed_at" field.
func BilledAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldBilledAt, v))
}

// BilledAtLT applies the LT predicate on the "billed_at" field.
func BilledAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldBilledAt, v))
}

// BilledAtLTE applies the LTE predicate on the "billed_at" field.
func BilledAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldBilledAt, v))
}

// BilledAtIsNil applies the IsNil predicate on the "billed_at" field.
func BilledAtIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldBilledAt))
}

// BilledAtNotNil applies the NotNil predicate on the "billed_at" field.
func BilledAtNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldBilledAt))
}

// RefundedAtEQ applies the EQ predicate on the "refunded_at" field.
func RefundedAtEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldEQ(FieldRefundedAt, v))
}

// RefundedAtNEQ applies the NEQ predicate on the "refunded_at" field.
func RefundedAtNEQ(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNEQ(FieldRefundedAt, v))
}

// RefundedAtIn applies the In predicate on the "refunded_at" field.
func RefundedAtIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIn(FieldRefundedAt, vs...))
}

// RefundedAtNotIn applies the NotIn predicate on the "refunded_at" field.
func RefundedAtNotIn(vs ...time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotIn(FieldRefundedAt, vs...))
}

// RefundedAtGT applies the GT predicate on the "refunded_at" field.
func RefundedAtGT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGT(FieldRefundedAt, v))
}

// RefundedAtGTE applies the GTE predicate on the "refunded_at" field.
func RefundedAtGTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldGTE(FieldRefundedAt, v))
}

// RefundedAtLT applies the LT predicate on the "refunded_at" field.
func RefundedAtLT(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLT(FieldRefundedAt, v))
}

// RefundedAtLTE applies the LTE predicate on the "refunded_at" field.
func RefundedAtLTE(v time.Time) predicate.VideoTask {
	return predicate.VideoTask(sql.FieldLTE(FieldRefundedAt, v))
}

// RefundedAtIsNil applies the IsNil predicate on the "refunded_at" field.
func RefundedAtIsNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldIsNull(FieldRefundedAt))
}

// RefundedAtNotNil applies the NotNil predicate on the "refunded_at" field.
func RefundedAtNotNil() predicate.VideoTask {
	return predicate.VideoTask(sql.FieldNotNull(FieldRefundedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.VideoTask {
	return predicate.VideoTask(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoTask) predicate.VideoTask {
	return predicate.VideoTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoTask) predicate.VideoTask {
	return predicate.VideoTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoTask) predicate.VideoTask {
	return predicate.VideoTask(sql.NotPredicates(p))
}
