// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/videogrouppricingrule"
)

// VideoGroupPricingRule is the model entity for the VideoGroupPricingRule schema.
type VideoGroupPricingRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// ModelCode holds the value of the "model_code" field.
	ModelCode string `json:"model_code,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution string `json:"resolution,omitempty"`
	// CreditsPerSecond holds the value of the "credits_per_second" field.
	CreditsPerSecond float64 `json:"credits_per_second,omitempty"`
	// ReferenceVideoMultiplier holds the value of the "reference_video_multiplier" field.
	ReferenceVideoMultiplier float64 `json:"reference_video_multiplier,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VideoGroupPricingRuleQuery when eager-loading is set.
	Edges        VideoGroupPricingRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VideoGroupPricingRuleEdges holds the relations/edges for other nodes in the graph.
type VideoGroupPricingRuleEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VideoGroupPricingRuleEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoGroupPricingRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videogrouppricingrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case videogrouppricingrule.FieldCreditsPerSecond, videogrouppricingrule.FieldReferenceVideoMultiplier:
			values[i] = new(sql.NullFloat64)
		case videogrouppricingrule.FieldID, videogrouppricingrule.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case videogrouppricingrule.FieldModelCode, videogrouppricingrule.FieldResolution:
			values[i] = new(sql.NullString)
		case videogrouppricingrule.FieldCreatedAt, videogrouppricingrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoGroupPricingRule fields.
func (_m *VideoGroupPricingRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videogrouppricingrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videogrouppricingrule.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case videogrouppricingrule.FieldModelCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_code", values[i])
			} else if value.Valid {
				_m.ModelCode = value.String
			}
		case videogrouppricingrule.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case videogrouppricingrule.FieldCreditsPerSecond:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field credits_per_second", values[i])
			} else if value.Valid {
				_m.CreditsPerSecond = value.Float64
			}
		case videogrouppricingrule.FieldReferenceVideoMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reference_video_multiplier", values[i])
			} else if value.Valid {
				_m.ReferenceVideoMultiplier = value.Float64
			}
		case videogrouppricingrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case videogrouppricingrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videogrouppricingrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoGroupPricingRule.
// This includes values selected through modifiers, order, etc.
func (_m *VideoGroupPricingRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the VideoGroupPricingRule entity.
func (_m *VideoGroupPricingRule) QueryGroup() *GroupQuery {
	return NewVideoGroupPricingRuleClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this VideoGroupPricingRule.
// Note that you need to call VideoGroupPricingRule.Unwrap() before calling this method if this VideoGroupPricingRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoGroupPricingRule) Update() *VideoGroupPricingRuleUpdateOne {
	return NewVideoGroupPricingRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoGroupPricingRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoGroupPricingRule) Unwrap() *VideoGroupPricingRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoGroupPricingRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoGroupPricingRule) String() string {
	var builder strings.Builder
	builder.WriteString("VideoGroupPricingRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("model_code=")
	builder.WriteString(_m.ModelCode)
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("credits_per_second=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreditsPerSecond))
	builder.WriteString(", ")
	builder.WriteString("reference_video_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferenceVideoMultiplier))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VideoGroupPricingRules is a parsable slice of VideoGroupPricingRule.
type VideoGroupPricingRules []*VideoGroupPricingRule
