// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskUpdate is the builder for updating VideoTask entities.
type VideoTaskUpdate struct {
	config
	hooks    []Hook
	mutation *VideoTaskMutation
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdate) Where(ps ...predicate.VideoTask) *VideoTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *VideoTaskUpdate) SetPublicID(v string) *VideoTaskUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillablePublicID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *VideoTaskUpdate) SetRequestID(v string) *VideoTaskUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRequestID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *VideoTaskUpdate) ClearRequestID() *VideoTaskUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdate) SetUserID(v int64) *VideoTaskUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUserID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdate) SetAPIKeyID(v int64) *VideoTaskUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAPIKeyID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdate) SetGroupID(v int64) *VideoTaskUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableGroupID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdate) SetAccountID(v int64) *VideoTaskUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableAccountID(v *int64) *VideoTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *VideoTaskUpdate) SetModel(v string) *VideoTaskUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *VideoTaskUpdate) SetUpstreamModel(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamModel(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *VideoTaskUpdate) SetResolution(v string) *VideoTaskUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResolution(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *VideoTaskUpdate) SetDurationSeconds(v int) *VideoTaskUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableDurationSeconds(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *VideoTaskUpdate) AddDurationSeconds(v int) *VideoTaskUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetReferenceDurationSeconds sets the "reference_duration_seconds" field.
func (_u *VideoTaskUpdate) SetReferenceDurationSeconds(v int) *VideoTaskUpdate {
	_u.mutation.ResetReferenceDurationSeconds()
	_u.mutation.SetReferenceDurationSeconds(v)
	return _u
}

// SetNillableReferenceDurationSeconds sets the "reference_duration_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableReferenceDurationSeconds(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetReferenceDurationSeconds(*v)
	}
	return _u
}

// AddReferenceDurationSeconds adds value to the "reference_duration_seconds" field.
func (_u *VideoTaskUpdate) AddReferenceDurationSeconds(v int) *VideoTaskUpdate {
	_u.mutation.AddReferenceDurationSeconds(v)
	return _u
}

// SetBillableSeconds sets the "billable_seconds" field.
func (_u *VideoTaskUpdate) SetBillableSeconds(v int) *VideoTaskUpdate {
	_u.mutation.ResetBillableSeconds()
	_u.mutation.SetBillableSeconds(v)
	return _u
}

// SetNillableBillableSeconds sets the "billable_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBillableSeconds(v *int) *VideoTaskUpdate {
	if v != nil {
		_u.SetBillableSeconds(*v)
	}
	return _u
}

// AddBillableSeconds adds value to the "billable_seconds" field.
func (_u *VideoTaskUpdate) AddBillableSeconds(v int) *VideoTaskUpdate {
	_u.mutation.AddBillableSeconds(v)
	return _u
}

// SetCostPerSecond sets the "cost_per_second" field.
func (_u *VideoTaskUpdate) SetCostPerSecond(v float64) *VideoTaskUpdate {
	_u.mutation.ResetCostPerSecond()
	_u.mutation.SetCostPerSecond(v)
	return _u
}

// SetNillableCostPerSecond sets the "cost_per_second" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableCostPerSecond(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetCostPerSecond(*v)
	}
	return _u
}

// AddCostPerSecond adds value to the "cost_per_second" field.
func (_u *VideoTaskUpdate) AddCostPerSecond(v float64) *VideoTaskUpdate {
	_u.mutation.AddCostPerSecond(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *VideoTaskUpdate) SetTotalCost(v float64) *VideoTaskUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableTotalCost(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *VideoTaskUpdate) AddTotalCost(v float64) *VideoTaskUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *VideoTaskUpdate) SetActualCost(v float64) *VideoTaskUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableActualCost(v *float64) *VideoTaskUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *VideoTaskUpdate) AddActualCost(v float64) *VideoTaskUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdate) SetStatus(v string) *VideoTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableStatus(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdate) SetUpstreamTaskID(v string) *VideoTaskUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *VideoTaskUpdate) ClearUpstreamTaskID() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetRequestJSON sets the "request_json" field.
func (_u *VideoTaskUpdate) SetRequestJSON(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetRequestJSON(v)
	return _u
}

// ClearRequestJSON clears the value of the "request_json" field.
func (_u *VideoTaskUpdate) ClearRequestJSON() *VideoTaskUpdate {
	_u.mutation.ClearRequestJSON()
	return _u
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (_u *VideoTaskUpdate) SetUpstreamResponseJSON(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetUpstreamResponseJSON(v)
	return _u
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (_u *VideoTaskUpdate) ClearUpstreamResponseJSON() *VideoTaskUpdate {
	_u.mutation.ClearUpstreamResponseJSON()
	return _u
}

// SetErrorJSON sets the "error_json" field.
func (_u *VideoTaskUpdate) SetErrorJSON(v map[string]interface{}) *VideoTaskUpdate {
	_u.mutation.SetErrorJSON(v)
	return _u
}

// ClearErrorJSON clears the value of the "error_json" field.
func (_u *VideoTaskUpdate) ClearErrorJSON() *VideoTaskUpdate {
	_u.mutation.ClearErrorJSON()
	return _u
}

// SetResultVideoURL sets the "result_video_url" field.
func (_u *VideoTaskUpdate) SetResultVideoURL(v string) *VideoTaskUpdate {
	_u.mutation.SetResultVideoURL(v)
	return _u
}

// SetNillableResultVideoURL sets the "result_video_url" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableResultVideoURL(v *string) *VideoTaskUpdate {
	if v != nil {
		_u.SetResultVideoURL(*v)
	}
	return _u
}

// ClearResultVideoURL clears the value of the "result_video_url" field.
func (_u *VideoTaskUpdate) ClearResultVideoURL() *VideoTaskUpdate {
	_u.mutation.ClearResultVideoURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdate) SetUpdatedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *VideoTaskUpdate) SetCompletedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableCompletedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *VideoTaskUpdate) ClearCompletedAt() *VideoTaskUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetBilledAt sets the "billed_at" field.
func (_u *VideoTaskUpdate) SetBilledAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetBilledAt(v)
	return _u
}

// SetNillableBilledAt sets the "billed_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableBilledAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetBilledAt(*v)
	}
	return _u
}

// ClearBilledAt clears the value of the "billed_at" field.
func (_u *VideoTaskUpdate) ClearBilledAt() *VideoTaskUpdate {
	_u.mutation.ClearBilledAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *VideoTaskUpdate) SetRefundedAt(v time.Time) *VideoTaskUpdate {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *VideoTaskUpdate) SetNillableRefundedAt(v *time.Time) *VideoTaskUpdate {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *VideoTaskUpdate) ClearRefundedAt() *VideoTaskUpdate {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VideoTaskUpdate) SetUser(v *User) *VideoTaskUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *VideoTaskUpdate) SetAPIKey(v *APIKey) *VideoTaskUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *VideoTaskUpdate) SetGroup(v *Group) *VideoTaskUpdate {
	return _u.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *VideoTaskUpdate) SetAccount(v *Account) *VideoTaskUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdate) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VideoTaskUpdate) ClearUser() *VideoTaskUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *VideoTaskUpdate) ClearAPIKey() *VideoTaskUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *VideoTaskUpdate) ClearGroup() *VideoTaskUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *VideoTaskUpdate) ClearAccount() *VideoTaskUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdate) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := videotask.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := videotask.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := videotask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := videotask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoTask.resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.account"`)
	}
	return nil
}

func (_u *VideoTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(videotask.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(videotask.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(videotask.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(videotask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(videotask.FieldResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(videotask.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(videotask.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReferenceDurationSeconds(); ok {
		_spec.SetField(videotask.FieldReferenceDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferenceDurationSeconds(); ok {
		_spec.AddField(videotask.FieldReferenceDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BillableSeconds(); ok {
		_spec.SetField(videotask.FieldBillableSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBillableSeconds(); ok {
		_spec.AddField(videotask.FieldBillableSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostPerSecond(); ok {
		_spec.SetField(videotask.FieldCostPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostPerSecond(); ok {
		_spec.AddField(videotask.FieldCostPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(videotask.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(videotask.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(videotask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(videotask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(videotask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestJSON(); ok {
		_spec.SetField(videotask.FieldRequestJSON, field.TypeJSON, value)
	}
	if _u.mutation.RequestJSONCleared() {
		_spec.ClearField(videotask.FieldRequestJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamResponseJSON(); ok {
		_spec.SetField(videotask.FieldUpstreamResponseJSON, field.TypeJSON, value)
	}
	if _u.mutation.UpstreamResponseJSONCleared() {
		_spec.ClearField(videotask.FieldUpstreamResponseJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorJSON(); ok {
		_spec.SetField(videotask.FieldErrorJSON, field.TypeJSON, value)
	}
	if _u.mutation.ErrorJSONCleared() {
		_spec.ClearField(videotask.FieldErrorJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultVideoURL(); ok {
		_spec.SetField(videotask.FieldResultVideoURL, field.TypeString, value)
	}
	if _u.mutation.ResultVideoURLCleared() {
		_spec.ClearField(videotask.FieldResultVideoURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(videotask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(videotask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BilledAt(); ok {
		_spec.SetField(videotask.FieldBilledAt, field.TypeTime, value)
	}
	if _u.mutation.BilledAtCleared() {
		_spec.ClearField(videotask.FieldBilledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(videotask.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(videotask.FieldRefundedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.UserTable,
			Columns: []string{videotask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.UserTable,
			Columns: []string{videotask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.APIKeyTable,
			Columns: []string{videotask.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.APIKeyTable,
			Columns: []string{videotask.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.GroupTable,
			Columns: []string{videotask.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.GroupTable,
			Columns: []string{videotask.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.AccountTable,
			Columns: []string{videotask.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.AccountTable,
			Columns: []string{videotask.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoTaskUpdateOne is the builder for updating a single VideoTask entity.
type VideoTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoTaskMutation
}

// SetPublicID sets the "public_id" field.
func (_u *VideoTaskUpdateOne) SetPublicID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillablePublicID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *VideoTaskUpdateOne) SetRequestID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRequestID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *VideoTaskUpdateOne) ClearRequestID() *VideoTaskUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *VideoTaskUpdateOne) SetUserID(v int64) *VideoTaskUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUserID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *VideoTaskUpdateOne) SetAPIKeyID(v int64) *VideoTaskUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAPIKeyID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoTaskUpdateOne) SetGroupID(v int64) *VideoTaskUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableGroupID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *VideoTaskUpdateOne) SetAccountID(v int64) *VideoTaskUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableAccountID(v *int64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *VideoTaskUpdateOne) SetModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *VideoTaskUpdateOne) SetUpstreamModel(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamModel(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *VideoTaskUpdateOne) SetResolution(v string) *VideoTaskUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResolution(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *VideoTaskUpdateOne) SetDurationSeconds(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableDurationSeconds(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *VideoTaskUpdateOne) AddDurationSeconds(v int) *VideoTaskUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetReferenceDurationSeconds sets the "reference_duration_seconds" field.
func (_u *VideoTaskUpdateOne) SetReferenceDurationSeconds(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetReferenceDurationSeconds()
	_u.mutation.SetReferenceDurationSeconds(v)
	return _u
}

// SetNillableReferenceDurationSeconds sets the "reference_duration_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableReferenceDurationSeconds(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetReferenceDurationSeconds(*v)
	}
	return _u
}

// AddReferenceDurationSeconds adds value to the "reference_duration_seconds" field.
func (_u *VideoTaskUpdateOne) AddReferenceDurationSeconds(v int) *VideoTaskUpdateOne {
	_u.mutation.AddReferenceDurationSeconds(v)
	return _u
}

// SetBillableSeconds sets the "billable_seconds" field.
func (_u *VideoTaskUpdateOne) SetBillableSeconds(v int) *VideoTaskUpdateOne {
	_u.mutation.ResetBillableSeconds()
	_u.mutation.SetBillableSeconds(v)
	return _u
}

// SetNillableBillableSeconds sets the "billable_seconds" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBillableSeconds(v *int) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBillableSeconds(*v)
	}
	return _u
}

// AddBillableSeconds adds value to the "billable_seconds" field.
func (_u *VideoTaskUpdateOne) AddBillableSeconds(v int) *VideoTaskUpdateOne {
	_u.mutation.AddBillableSeconds(v)
	return _u
}

// SetCostPerSecond sets the "cost_per_second" field.
func (_u *VideoTaskUpdateOne) SetCostPerSecond(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetCostPerSecond()
	_u.mutation.SetCostPerSecond(v)
	return _u
}

// SetNillableCostPerSecond sets the "cost_per_second" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableCostPerSecond(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetCostPerSecond(*v)
	}
	return _u
}

// AddCostPerSecond adds value to the "cost_per_second" field.
func (_u *VideoTaskUpdateOne) AddCostPerSecond(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddCostPerSecond(v)
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *VideoTaskUpdateOne) SetTotalCost(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableTotalCost(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *VideoTaskUpdateOne) AddTotalCost(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *VideoTaskUpdateOne) SetActualCost(v float64) *VideoTaskUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableActualCost(v *float64) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *VideoTaskUpdateOne) AddActualCost(v float64) *VideoTaskUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoTaskUpdateOne) SetStatus(v string) *VideoTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableStatus(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) SetUpstreamTaskID(v string) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableUpstreamTaskID(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamTaskID() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetRequestJSON sets the "request_json" field.
func (_u *VideoTaskUpdateOne) SetRequestJSON(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetRequestJSON(v)
	return _u
}

// ClearRequestJSON clears the value of the "request_json" field.
func (_u *VideoTaskUpdateOne) ClearRequestJSON() *VideoTaskUpdateOne {
	_u.mutation.ClearRequestJSON()
	return _u
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (_u *VideoTaskUpdateOne) SetUpstreamResponseJSON(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetUpstreamResponseJSON(v)
	return _u
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (_u *VideoTaskUpdateOne) ClearUpstreamResponseJSON() *VideoTaskUpdateOne {
	_u.mutation.ClearUpstreamResponseJSON()
	return _u
}

// SetErrorJSON sets the "error_json" field.
func (_u *VideoTaskUpdateOne) SetErrorJSON(v map[string]interface{}) *VideoTaskUpdateOne {
	_u.mutation.SetErrorJSON(v)
	return _u
}

// ClearErrorJSON clears the value of the "error_json" field.
func (_u *VideoTaskUpdateOne) ClearErrorJSON() *VideoTaskUpdateOne {
	_u.mutation.ClearErrorJSON()
	return _u
}

// SetResultVideoURL sets the "result_video_url" field.
func (_u *VideoTaskUpdateOne) SetResultVideoURL(v string) *VideoTaskUpdateOne {
	_u.mutation.SetResultVideoURL(v)
	return _u
}

// SetNillableResultVideoURL sets the "result_video_url" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableResultVideoURL(v *string) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetResultVideoURL(*v)
	}
	return _u
}

// ClearResultVideoURL clears the value of the "result_video_url" field.
func (_u *VideoTaskUpdateOne) ClearResultVideoURL() *VideoTaskUpdateOne {
	_u.mutation.ClearResultVideoURL()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoTaskUpdateOne) SetUpdatedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *VideoTaskUpdateOne) SetCompletedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableCompletedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *VideoTaskUpdateOne) ClearCompletedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetBilledAt sets the "billed_at" field.
func (_u *VideoTaskUpdateOne) SetBilledAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetBilledAt(v)
	return _u
}

// SetNillableBilledAt sets the "billed_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableBilledAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetBilledAt(*v)
	}
	return _u
}

// ClearBilledAt clears the value of the "billed_at" field.
func (_u *VideoTaskUpdateOne) ClearBilledAt() *VideoTaskUpdateOne {
	_u.mutation.ClearBilledAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *VideoTaskUpdateOne) SetRefundedAt(v time.Time) *VideoTaskUpdateOne {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *VideoTaskUpdateOne) SetNillableRefundedAt(v *time.Time) *VideoTaskUpdateOne {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *VideoTaskUpdateOne) ClearRefundedAt() *VideoTaskUpdateOne {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *VideoTaskUpdateOne) SetUser(v *User) *VideoTaskUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *VideoTaskUpdateOne) SetAPIKey(v *APIKey) *VideoTaskUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *VideoTaskUpdateOne) SetGroup(v *Group) *VideoTaskUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *VideoTaskUpdateOne) SetAccount(v *Account) *VideoTaskUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_u *VideoTaskUpdateOne) Mutation() *VideoTaskMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *VideoTaskUpdateOne) ClearUser() *VideoTaskUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *VideoTaskUpdateOne) ClearAPIKey() *VideoTaskUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *VideoTaskUpdateOne) ClearGroup() *VideoTaskUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *VideoTaskUpdateOne) ClearAccount() *VideoTaskUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the VideoTaskUpdate builder.
func (_u *VideoTaskUpdateOne) Where(ps ...predicate.VideoTask) *VideoTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoTaskUpdateOne) Select(field string, fields ...string) *VideoTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoTask entity.
func (_u *VideoTaskUpdateOne) Save(ctx context.Context) (*VideoTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) SaveX(ctx context.Context) *VideoTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videotask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoTaskUpdateOne) check() error {
	if v, ok := _u.mutation.PublicID(); ok {
		if err := videotask.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.public_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := videotask.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := videotask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := videotask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoTask.resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.api_key"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoTask.account"`)
	}
	return nil
}

func (_u *VideoTaskUpdateOne) sqlSave(ctx context.Context) (_node *VideoTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videotask.Table, videotask.Columns, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videotask.FieldID)
		for _, f := range fields {
			if !videotask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videotask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(videotask.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(videotask.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(videotask.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(videotask.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(videotask.FieldResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(videotask.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(videotask.FieldDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReferenceDurationSeconds(); ok {
		_spec.SetField(videotask.FieldReferenceDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReferenceDurationSeconds(); ok {
		_spec.AddField(videotask.FieldReferenceDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BillableSeconds(); ok {
		_spec.SetField(videotask.FieldBillableSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBillableSeconds(); ok {
		_spec.AddField(videotask.FieldBillableSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CostPerSecond(); ok {
		_spec.SetField(videotask.FieldCostPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostPerSecond(); ok {
		_spec.AddField(videotask.FieldCostPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(videotask.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(videotask.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(videotask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(videotask.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(videotask.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.RequestJSON(); ok {
		_spec.SetField(videotask.FieldRequestJSON, field.TypeJSON, value)
	}
	if _u.mutation.RequestJSONCleared() {
		_spec.ClearField(videotask.FieldRequestJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpstreamResponseJSON(); ok {
		_spec.SetField(videotask.FieldUpstreamResponseJSON, field.TypeJSON, value)
	}
	if _u.mutation.UpstreamResponseJSONCleared() {
		_spec.ClearField(videotask.FieldUpstreamResponseJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorJSON(); ok {
		_spec.SetField(videotask.FieldErrorJSON, field.TypeJSON, value)
	}
	if _u.mutation.ErrorJSONCleared() {
		_spec.ClearField(videotask.FieldErrorJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResultVideoURL(); ok {
		_spec.SetField(videotask.FieldResultVideoURL, field.TypeString, value)
	}
	if _u.mutation.ResultVideoURLCleared() {
		_spec.ClearField(videotask.FieldResultVideoURL, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(videotask.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(videotask.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BilledAt(); ok {
		_spec.SetField(videotask.FieldBilledAt, field.TypeTime, value)
	}
	if _u.mutation.BilledAtCleared() {
		_spec.ClearField(videotask.FieldBilledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(videotask.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(videotask.FieldRefundedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.UserTable,
			Columns: []string{videotask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.UserTable,
			Columns: []string{videotask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.APIKeyTable,
			Columns: []string{videotask.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.APIKeyTable,
			Columns: []string{videotask.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.GroupTable,
			Columns: []string{videotask.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.GroupTable,
			Columns: []string{videotask.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.AccountTable,
			Columns: []string{videotask.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.AccountTable,
			Columns: []string{videotask.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VideoTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videotask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
