// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/videogrouppricingrule"
)

// VideoGroupPricingRuleCreate is the builder for creating a VideoGroupPricingRule entity.
type VideoGroupPricingRuleCreate struct {
	config
	mutation *VideoGroupPricingRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *VideoGroupPricingRuleCreate) SetGroupID(v int64) *VideoGroupPricingRuleCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetModelCode sets the "model_code" field.
func (_c *VideoGroupPricingRuleCreate) SetModelCode(v string) *VideoGroupPricingRuleCreate {
	_c.mutation.SetModelCode(v)
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *VideoGroupPricingRuleCreate) SetResolution(v string) *VideoGroupPricingRuleCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetCreditsPerSecond sets the "credits_per_second" field.
func (_c *VideoGroupPricingRuleCreate) SetCreditsPerSecond(v float64) *VideoGroupPricingRuleCreate {
	_c.mutation.SetCreditsPerSecond(v)
	return _c
}

// SetReferenceVideoMultiplier sets the "reference_video_multiplier" field.
func (_c *VideoGroupPricingRuleCreate) SetReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleCreate {
	_c.mutation.SetReferenceVideoMultiplier(v)
	return _c
}

// SetNillableReferenceVideoMultiplier sets the "reference_video_multiplier" field if the given value is not nil.
func (_c *VideoGroupPricingRuleCreate) SetNillableReferenceVideoMultiplier(v *float64) *VideoGroupPricingRuleCreate {
	if v != nil {
		_c.SetReferenceVideoMultiplier(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *VideoGroupPricingRuleCreate) SetEnabled(v bool) *VideoGroupPricingRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *VideoGroupPricingRuleCreate) SetNillableEnabled(v *bool) *VideoGroupPricingRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoGroupPricingRuleCreate) SetCreatedAt(v time.Time) *VideoGroupPricingRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoGroupPricingRuleCreate) SetNillableCreatedAt(v *time.Time) *VideoGroupPricingRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoGroupPricingRuleCreate) SetUpdatedAt(v time.Time) *VideoGroupPricingRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoGroupPricingRuleCreate) SetNillableUpdatedAt(v *time.Time) *VideoGroupPricingRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *VideoGroupPricingRuleCreate) SetGroup(v *Group) *VideoGroupPricingRuleCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the VideoGroupPricingRuleMutation object of the builder.
func (_c *VideoGroupPricingRuleCreate) Mutation() *VideoGroupPricingRuleMutation {
	return _c.mutation
}

// Save creates the VideoGroupPricingRule in the database.
func (_c *VideoGroupPricingRuleCreate) Save(ctx context.Context) (*VideoGroupPricingRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoGroupPricingRuleCreate) SaveX(ctx context.Context) *VideoGroupPricingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoGroupPricingRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoGroupPricingRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoGroupPricingRuleCreate) defaults() {
	if _, ok := _c.mutation.ReferenceVideoMultiplier(); !ok {
		v := videogrouppricingrule.DefaultReferenceVideoMultiplier
		_c.mutation.SetReferenceVideoMultiplier(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := videogrouppricingrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videogrouppricingrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videogrouppricingrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoGroupPricingRuleCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoGroupPricingRule.group_id"`)}
	}
	if _, ok := _c.mutation.ModelCode(); !ok {
		return &ValidationError{Name: "model_code", err: errors.New(`ent: missing required field "VideoGroupPricingRule.model_code"`)}
	}
	if v, ok := _c.mutation.ModelCode(); ok {
		if err := videogrouppricingrule.ModelCodeValidator(v); err != nil {
			return &ValidationError{Name: "model_code", err: fmt.Errorf(`ent: validator failed for field "VideoGroupPricingRule.model_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Resolution(); !ok {
		return &ValidationError{Name: "resolution", err: errors.New(`ent: missing required field "VideoGroupPricingRule.resolution"`)}
	}
	if v, ok := _c.mutation.Resolution(); ok {
		if err := videogrouppricingrule.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoGroupPricingRule.resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreditsPerSecond(); !ok {
		return &ValidationError{Name: "credits_per_second", err: errors.New(`ent: missing required field "VideoGroupPricingRule.credits_per_second"`)}
	}
	if _, ok := _c.mutation.ReferenceVideoMultiplier(); !ok {
		return &ValidationError{Name: "reference_video_multiplier", err: errors.New(`ent: missing required field "VideoGroupPricingRule.reference_video_multiplier"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "VideoGroupPricingRule.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoGroupPricingRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoGroupPricingRule.updated_at"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "VideoGroupPricingRule.group"`)}
	}
	return nil
}

func (_c *VideoGroupPricingRuleCreate) sqlSave(ctx context.Context) (*VideoGroupPricingRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoGroupPricingRuleCreate) createSpec() (*VideoGroupPricingRule, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoGroupPricingRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videogrouppricingrule.Table, sqlgraph.NewFieldSpec(videogrouppricingrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ModelCode(); ok {
		_spec.SetField(videogrouppricingrule.FieldModelCode, field.TypeString, value)
		_node.ModelCode = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(videogrouppricingrule.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.CreditsPerSecond(); ok {
		_spec.SetField(videogrouppricingrule.FieldCreditsPerSecond, field.TypeFloat64, value)
		_node.CreditsPerSecond = value
	}
	if value, ok := _c.mutation.ReferenceVideoMultiplier(); ok {
		_spec.SetField(videogrouppricingrule.FieldReferenceVideoMultiplier, field.TypeFloat64, value)
		_node.ReferenceVideoMultiplier = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(videogrouppricingrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videogrouppricingrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videogrouppricingrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videogrouppricingrule.GroupTable,
			Columns: []string{videogrouppricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoGroupPricingRule.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoGroupPricingRuleUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoGroupPricingRuleCreate) OnConflict(opts ...sql.ConflictOption) *VideoGroupPricingRuleUpsertOne {
	_c.conflict = opts
	return &VideoGroupPricingRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoGroupPricingRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoGroupPricingRuleCreate) OnConflictColumns(columns ...string) *VideoGroupPricingRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoGroupPricingRuleUpsertOne{
		create: _c,
	}
}

type (
	// VideoGroupPricingRuleUpsertOne is the builder for "upsert"-ing
	//  one VideoGroupPricingRule node.
	VideoGroupPricingRuleUpsertOne struct {
		create *VideoGroupPricingRuleCreate
	}

	// VideoGroupPricingRuleUpsert is the "OnConflict" setter.
	VideoGroupPricingRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *VideoGroupPricingRuleUpsert) SetGroupID(v int64) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateGroupID() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldGroupID)
	return u
}

// SetModelCode sets the "model_code" field.
func (u *VideoGroupPricingRuleUpsert) SetModelCode(v string) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldModelCode, v)
	return u
}

// UpdateModelCode sets the "model_code" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateModelCode() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldModelCode)
	return u
}

// SetResolution sets the "resolution" field.
func (u *VideoGroupPricingRuleUpsert) SetResolution(v string) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldResolution, v)
	return u
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateResolution() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldResolution)
	return u
}

// SetCreditsPerSecond sets the "credits_per_second" field.
func (u *VideoGroupPricingRuleUpsert) SetCreditsPerSecond(v float64) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldCreditsPerSecond, v)
	return u
}

// UpdateCreditsPerSecond sets the "credits_per_second" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateCreditsPerSecond() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldCreditsPerSecond)
	return u
}

// AddCreditsPerSecond adds v to the "credits_per_second" field.
func (u *VideoGroupPricingRuleUpsert) AddCreditsPerSecond(v float64) *VideoGroupPricingRuleUpsert {
	u.Add(videogrouppricingrule.FieldCreditsPerSecond, v)
	return u
}

// SetReferenceVideoMultiplier sets the "reference_video_multiplier" field.
func (u *VideoGroupPricingRuleUpsert) SetReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldReferenceVideoMultiplier, v)
	return u
}

// UpdateReferenceVideoMultiplier sets the "reference_video_multiplier" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateReferenceVideoMultiplier() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldReferenceVideoMultiplier)
	return u
}

// AddReferenceVideoMultiplier adds v to the "reference_video_multiplier" field.
func (u *VideoGroupPricingRuleUpsert) AddReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpsert {
	u.Add(videogrouppricingrule.FieldReferenceVideoMultiplier, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *VideoGroupPricingRuleUpsert) SetEnabled(v bool) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateEnabled() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldEnabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoGroupPricingRuleUpsert) SetUpdatedAt(v time.Time) *VideoGroupPricingRuleUpsert {
	u.Set(videogrouppricingrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsert) UpdateUpdatedAt() *VideoGroupPricingRuleUpsert {
	u.SetExcluded(videogrouppricingrule.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoGroupPricingRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoGroupPricingRuleUpsertOne) UpdateNewValues() *VideoGroupPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videogrouppricingrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoGroupPricingRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoGroupPricingRuleUpsertOne) Ignore() *VideoGroupPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoGroupPricingRuleUpsertOne) DoNothing() *VideoGroupPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoGroupPricingRuleCreate.OnConflict
// documentation for more info.
func (u *VideoGroupPricingRuleUpsertOne) Update(set func(*VideoGroupPricingRuleUpsert)) *VideoGroupPricingRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoGroupPricingRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoGroupPricingRuleUpsertOne) SetGroupID(v int64) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateGroupID() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelCode sets the "model_code" field.
func (u *VideoGroupPricingRuleUpsertOne) SetModelCode(v string) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetModelCode(v)
	})
}

// UpdateModelCode sets the "model_code" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateModelCode() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateModelCode()
	})
}

// SetResolution sets the "resolution" field.
func (u *VideoGroupPricingRuleUpsertOne) SetResolution(v string) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateResolution() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateResolution()
	})
}

// SetCreditsPerSecond sets the "credits_per_second" field.
func (u *VideoGroupPricingRuleUpsertOne) SetCreditsPerSecond(v float64) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetCreditsPerSecond(v)
	})
}

// AddCreditsPerSecond adds v to the "credits_per_second" field.
func (u *VideoGroupPricingRuleUpsertOne) AddCreditsPerSecond(v float64) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.AddCreditsPerSecond(v)
	})
}

// UpdateCreditsPerSecond sets the "credits_per_second" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateCreditsPerSecond() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateCreditsPerSecond()
	})
}

// SetReferenceVideoMultiplier sets the "reference_video_multiplier" field.
func (u *VideoGroupPricingRuleUpsertOne) SetReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetReferenceVideoMultiplier(v)
	})
}

// AddReferenceVideoMultiplier adds v to the "reference_video_multiplier" field.
func (u *VideoGroupPricingRuleUpsertOne) AddReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.AddReferenceVideoMultiplier(v)
	})
}

// UpdateReferenceVideoMultiplier sets the "reference_video_multiplier" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateReferenceVideoMultiplier() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateReferenceVideoMultiplier()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VideoGroupPricingRuleUpsertOne) SetEnabled(v bool) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateEnabled() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoGroupPricingRuleUpsertOne) SetUpdatedAt(v time.Time) *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertOne) UpdateUpdatedAt() *VideoGroupPricingRuleUpsertOne {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VideoGroupPricingRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoGroupPricingRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoGroupPricingRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoGroupPricingRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoGroupPricingRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoGroupPricingRuleCreateBulk is the builder for creating many VideoGroupPricingRule entities in bulk.
type VideoGroupPricingRuleCreateBulk struct {
	config
	err      error
	builders []*VideoGroupPricingRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoGroupPricingRule entities in the database.
func (_c *VideoGroupPricingRuleCreateBulk) Save(ctx context.Context) ([]*VideoGroupPricingRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoGroupPricingRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoGroupPricingRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoGroupPricingRuleCreateBulk) SaveX(ctx context.Context) []*VideoGroupPricingRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoGroupPricingRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoGroupPricingRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoGroupPricingRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoGroupPricingRuleUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoGroupPricingRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoGroupPricingRuleUpsertBulk {
	_c.conflict = opts
	return &VideoGroupPricingRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoGroupPricingRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoGroupPricingRuleCreateBulk) OnConflictColumns(columns ...string) *VideoGroupPricingRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoGroupPricingRuleUpsertBulk{
		create: _c,
	}
}

// VideoGroupPricingRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoGroupPricingRule nodes.
type VideoGroupPricingRuleUpsertBulk struct {
	create *VideoGroupPricingRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoGroupPricingRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoGroupPricingRuleUpsertBulk) UpdateNewValues() *VideoGroupPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videogrouppricingrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoGroupPricingRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoGroupPricingRuleUpsertBulk) Ignore() *VideoGroupPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoGroupPricingRuleUpsertBulk) DoNothing() *VideoGroupPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoGroupPricingRuleCreateBulk.OnConflict
// documentation for more info.
func (u *VideoGroupPricingRuleUpsertBulk) Update(set func(*VideoGroupPricingRuleUpsert)) *VideoGroupPricingRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoGroupPricingRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetGroupID(v int64) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateGroupID() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateGroupID()
	})
}

// SetModelCode sets the "model_code" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetModelCode(v string) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetModelCode(v)
	})
}

// UpdateModelCode sets the "model_code" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateModelCode() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateModelCode()
	})
}

// SetResolution sets the "resolution" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetResolution(v string) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateResolution() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateResolution()
	})
}

// SetCreditsPerSecond sets the "credits_per_second" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetCreditsPerSecond(v float64) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetCreditsPerSecond(v)
	})
}

// AddCreditsPerSecond adds v to the "credits_per_second" field.
func (u *VideoGroupPricingRuleUpsertBulk) AddCreditsPerSecond(v float64) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.AddCreditsPerSecond(v)
	})
}

// UpdateCreditsPerSecond sets the "credits_per_second" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateCreditsPerSecond() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateCreditsPerSecond()
	})
}

// SetReferenceVideoMultiplier sets the "reference_video_multiplier" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetReferenceVideoMultiplier(v)
	})
}

// AddReferenceVideoMultiplier adds v to the "reference_video_multiplier" field.
func (u *VideoGroupPricingRuleUpsertBulk) AddReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.AddReferenceVideoMultiplier(v)
	})
}

// UpdateReferenceVideoMultiplier sets the "reference_video_multiplier" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateReferenceVideoMultiplier() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateReferenceVideoMultiplier()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetEnabled(v bool) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateEnabled() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoGroupPricingRuleUpsertBulk) SetUpdatedAt(v time.Time) *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoGroupPricingRuleUpsertBulk) UpdateUpdatedAt() *VideoGroupPricingRuleUpsertBulk {
	return u.Update(func(s *VideoGroupPricingRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *VideoGroupPricingRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoGroupPricingRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoGroupPricingRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoGroupPricingRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
