// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videogrouppricingrule"
)

// VideoGroupPricingRuleUpdate is the builder for updating VideoGroupPricingRule entities.
type VideoGroupPricingRuleUpdate struct {
	config
	hooks    []Hook
	mutation *VideoGroupPricingRuleMutation
}

// Where appends a list predicates to the VideoGroupPricingRuleUpdate builder.
func (_u *VideoGroupPricingRuleUpdate) Where(ps ...predicate.VideoGroupPricingRule) *VideoGroupPricingRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *VideoGroupPricingRuleUpdate) SetGroupID(v int64) *VideoGroupPricingRuleUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdate) SetNillableGroupID(v *int64) *VideoGroupPricingRuleUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModelCode sets the "model_code" field.
func (_u *VideoGroupPricingRuleUpdate) SetModelCode(v string) *VideoGroupPricingRuleUpdate {
	_u.mutation.SetModelCode(v)
	return _u
}

// SetNillableModelCode sets the "model_code" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdate) SetNillableModelCode(v *string) *VideoGroupPricingRuleUpdate {
	if v != nil {
		_u.SetModelCode(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *VideoGroupPricingRuleUpdate) SetResolution(v string) *VideoGroupPricingRuleUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdate) SetNillableResolution(v *string) *VideoGroupPricingRuleUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// SetCreditsPerSecond sets the "credits_per_second" field.
func (_u *VideoGroupPricingRuleUpdate) SetCreditsPerSecond(v float64) *VideoGroupPricingRuleUpdate {
	_u.mutation.ResetCreditsPerSecond()
	_u.mutation.SetCreditsPerSecond(v)
	return _u
}

// SetNillableCreditsPerSecond sets the "credits_per_second" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdate) SetNillableCreditsPerSecond(v *float64) *VideoGroupPricingRuleUpdate {
	if v != nil {
		_u.SetCreditsPerSecond(*v)
	}
	return _u
}

// AddCreditsPerSecond adds value to the "credits_per_second" field.
func (_u *VideoGroupPricingRuleUpdate) AddCreditsPerSecond(v float64) *VideoGroupPricingRuleUpdate {
	_u.mutation.AddCreditsPerSecond(v)
	return _u
}

// SetReferenceVideoMultiplier sets the "reference_video_multiplier" field.
func (_u *VideoGroupPricingRuleUpdate) SetReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpdate {
	_u.mutation.ResetReferenceVideoMultiplier()
	_u.mutation.SetReferenceVideoMultiplier(v)
	return _u
}

// SetNillableReferenceVideoMultiplier sets the "reference_video_multiplier" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdate) SetNillableReferenceVideoMultiplier(v *float64) *VideoGroupPricingRuleUpdate {
	if v != nil {
		_u.SetReferenceVideoMultiplier(*v)
	}
	return _u
}

// AddReferenceVideoMultiplier adds value to the "reference_video_multiplier" field.
func (_u *VideoGroupPricingRuleUpdate) AddReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpdate {
	_u.mutation.AddReferenceVideoMultiplier(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *VideoGroupPricingRuleUpdate) SetEnabled(v bool) *VideoGroupPricingRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdate) SetNillableEnabled(v *bool) *VideoGroupPricingRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoGroupPricingRuleUpdate) SetUpdatedAt(v time.Time) *VideoGroupPricingRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *VideoGroupPricingRuleUpdate) SetGroup(v *Group) *VideoGroupPricingRuleUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the VideoGroupPricingRuleMutation object of the builder.
func (_u *VideoGroupPricingRuleUpdate) Mutation() *VideoGroupPricingRuleMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *VideoGroupPricingRuleUpdate) ClearGroup() *VideoGroupPricingRuleUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoGroupPricingRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoGroupPricingRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoGroupPricingRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoGroupPricingRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoGroupPricingRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videogrouppricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoGroupPricingRuleUpdate) check() error {
	if v, ok := _u.mutation.ModelCode(); ok {
		if err := videogrouppricingrule.ModelCodeValidator(v); err != nil {
			return &ValidationError{Name: "model_code", err: fmt.Errorf(`ent: validator failed for field "VideoGroupPricingRule.model_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := videogrouppricingrule.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoGroupPricingRule.resolution": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoGroupPricingRule.group"`)
	}
	return nil
}

func (_u *VideoGroupPricingRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videogrouppricingrule.Table, videogrouppricingrule.Columns, sqlgraph.NewFieldSpec(videogrouppricingrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelCode(); ok {
		_spec.SetField(videogrouppricingrule.FieldModelCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(videogrouppricingrule.FieldResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditsPerSecond(); ok {
		_spec.SetField(videogrouppricingrule.FieldCreditsPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditsPerSecond(); ok {
		_spec.AddField(videogrouppricingrule.FieldCreditsPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReferenceVideoMultiplier(); ok {
		_spec.SetField(videogrouppricingrule.FieldReferenceVideoMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReferenceVideoMultiplier(); ok {
		_spec.AddField(videogrouppricingrule.FieldReferenceVideoMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(videogrouppricingrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videogrouppricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videogrouppricingrule.GroupTable,
			Columns: []string{videogrouppricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videogrouppricingrule.GroupTable,
			Columns: []string{videogrouppricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videogrouppricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoGroupPricingRuleUpdateOne is the builder for updating a single VideoGroupPricingRule entity.
type VideoGroupPricingRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoGroupPricingRuleMutation
}

// SetGroupID sets the "group_id" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetGroupID(v int64) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdateOne) SetNillableGroupID(v *int64) *VideoGroupPricingRuleUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetModelCode sets the "model_code" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetModelCode(v string) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.SetModelCode(v)
	return _u
}

// SetNillableModelCode sets the "model_code" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdateOne) SetNillableModelCode(v *string) *VideoGroupPricingRuleUpdateOne {
	if v != nil {
		_u.SetModelCode(*v)
	}
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetResolution(v string) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdateOne) SetNillableResolution(v *string) *VideoGroupPricingRuleUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// SetCreditsPerSecond sets the "credits_per_second" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetCreditsPerSecond(v float64) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.ResetCreditsPerSecond()
	_u.mutation.SetCreditsPerSecond(v)
	return _u
}

// SetNillableCreditsPerSecond sets the "credits_per_second" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdateOne) SetNillableCreditsPerSecond(v *float64) *VideoGroupPricingRuleUpdateOne {
	if v != nil {
		_u.SetCreditsPerSecond(*v)
	}
	return _u
}

// AddCreditsPerSecond adds value to the "credits_per_second" field.
func (_u *VideoGroupPricingRuleUpdateOne) AddCreditsPerSecond(v float64) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.AddCreditsPerSecond(v)
	return _u
}

// SetReferenceVideoMultiplier sets the "reference_video_multiplier" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.ResetReferenceVideoMultiplier()
	_u.mutation.SetReferenceVideoMultiplier(v)
	return _u
}

// SetNillableReferenceVideoMultiplier sets the "reference_video_multiplier" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdateOne) SetNillableReferenceVideoMultiplier(v *float64) *VideoGroupPricingRuleUpdateOne {
	if v != nil {
		_u.SetReferenceVideoMultiplier(*v)
	}
	return _u
}

// AddReferenceVideoMultiplier adds value to the "reference_video_multiplier" field.
func (_u *VideoGroupPricingRuleUpdateOne) AddReferenceVideoMultiplier(v float64) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.AddReferenceVideoMultiplier(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetEnabled(v bool) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *VideoGroupPricingRuleUpdateOne) SetNillableEnabled(v *bool) *VideoGroupPricingRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoGroupPricingRuleUpdateOne) SetUpdatedAt(v time.Time) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *VideoGroupPricingRuleUpdateOne) SetGroup(v *Group) *VideoGroupPricingRuleUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the VideoGroupPricingRuleMutation object of the builder.
func (_u *VideoGroupPricingRuleUpdateOne) Mutation() *VideoGroupPricingRuleMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *VideoGroupPricingRuleUpdateOne) ClearGroup() *VideoGroupPricingRuleUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the VideoGroupPricingRuleUpdate builder.
func (_u *VideoGroupPricingRuleUpdateOne) Where(ps ...predicate.VideoGroupPricingRule) *VideoGroupPricingRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoGroupPricingRuleUpdateOne) Select(field string, fields ...string) *VideoGroupPricingRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoGroupPricingRule entity.
func (_u *VideoGroupPricingRuleUpdateOne) Save(ctx context.Context) (*VideoGroupPricingRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoGroupPricingRuleUpdateOne) SaveX(ctx context.Context) *VideoGroupPricingRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoGroupPricingRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoGroupPricingRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoGroupPricingRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videogrouppricingrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoGroupPricingRuleUpdateOne) check() error {
	if v, ok := _u.mutation.ModelCode(); ok {
		if err := videogrouppricingrule.ModelCodeValidator(v); err != nil {
			return &ValidationError{Name: "model_code", err: fmt.Errorf(`ent: validator failed for field "VideoGroupPricingRule.model_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resolution(); ok {
		if err := videogrouppricingrule.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoGroupPricingRule.resolution": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "VideoGroupPricingRule.group"`)
	}
	return nil
}

func (_u *VideoGroupPricingRuleUpdateOne) sqlSave(ctx context.Context) (_node *VideoGroupPricingRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videogrouppricingrule.Table, videogrouppricingrule.Columns, sqlgraph.NewFieldSpec(videogrouppricingrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoGroupPricingRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videogrouppricingrule.FieldID)
		for _, f := range fields {
			if !videogrouppricingrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videogrouppricingrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ModelCode(); ok {
		_spec.SetField(videogrouppricingrule.FieldModelCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(videogrouppricingrule.FieldResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditsPerSecond(); ok {
		_spec.SetField(videogrouppricingrule.FieldCreditsPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditsPerSecond(); ok {
		_spec.AddField(videogrouppricingrule.FieldCreditsPerSecond, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReferenceVideoMultiplier(); ok {
		_spec.SetField(videogrouppricingrule.FieldReferenceVideoMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReferenceVideoMultiplier(); ok {
		_spec.AddField(videogrouppricingrule.FieldReferenceVideoMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(videogrouppricingrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videogrouppricingrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videogrouppricingrule.GroupTable,
			Columns: []string{videogrouppricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videogrouppricingrule.GroupTable,
			Columns: []string{videogrouppricingrule.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &VideoGroupPricingRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videogrouppricingrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
