// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskCreate is the builder for creating a VideoTask entity.
type VideoTaskCreate struct {
	config
	mutation *VideoTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPublicID sets the "public_id" field.
func (_c *VideoTaskCreate) SetPublicID(v string) *VideoTaskCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *VideoTaskCreate) SetRequestID(v string) *VideoTaskCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableRequestID(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VideoTaskCreate) SetUserID(v int64) *VideoTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *VideoTaskCreate) SetAPIKeyID(v int64) *VideoTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *VideoTaskCreate) SetGroupID(v int64) *VideoTaskCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *VideoTaskCreate) SetAccountID(v int64) *VideoTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VideoTaskCreate) SetModel(v string) *VideoTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *VideoTaskCreate) SetUpstreamModel(v string) *VideoTaskCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *VideoTaskCreate) SetResolution(v string) *VideoTaskCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *VideoTaskCreate) SetDurationSeconds(v int) *VideoTaskCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableDurationSeconds(v *int) *VideoTaskCreate {
	if v != nil {
		_c.SetDurationSeconds(*v)
	}
	return _c
}

// SetReferenceDurationSeconds sets the "reference_duration_seconds" field.
func (_c *VideoTaskCreate) SetReferenceDurationSeconds(v int) *VideoTaskCreate {
	_c.mutation.SetReferenceDurationSeconds(v)
	return _c
}

// SetNillableReferenceDurationSeconds sets the "reference_duration_seconds" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableReferenceDurationSeconds(v *int) *VideoTaskCreate {
	if v != nil {
		_c.SetReferenceDurationSeconds(*v)
	}
	return _c
}

// SetBillableSeconds sets the "billable_seconds" field.
func (_c *VideoTaskCreate) SetBillableSeconds(v int) *VideoTaskCreate {
	_c.mutation.SetBillableSeconds(v)
	return _c
}

// SetNillableBillableSeconds sets the "billable_seconds" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableBillableSeconds(v *int) *VideoTaskCreate {
	if v != nil {
		_c.SetBillableSeconds(*v)
	}
	return _c
}

// SetCostPerSecond sets the "cost_per_second" field.
func (_c *VideoTaskCreate) SetCostPerSecond(v float64) *VideoTaskCreate {
	_c.mutation.SetCostPerSecond(v)
	return _c
}

// SetNillableCostPerSecond sets the "cost_per_second" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableCostPerSecond(v *float64) *VideoTaskCreate {
	if v != nil {
		_c.SetCostPerSecond(*v)
	}
	return _c
}

// SetTotalCost sets the "total_cost" field.
func (_c *VideoTaskCreate) SetTotalCost(v float64) *VideoTaskCreate {
	_c.mutation.SetTotalCost(v)
	return _c
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableTotalCost(v *float64) *VideoTaskCreate {
	if v != nil {
		_c.SetTotalCost(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *VideoTaskCreate) SetActualCost(v float64) *VideoTaskCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableActualCost(v *float64) *VideoTaskCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoTaskCreate) SetStatus(v string) *VideoTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableStatus(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *VideoTaskCreate) SetUpstreamTaskID(v string) *VideoTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableUpstreamTaskID(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetUpstreamTaskID(*v)
	}
	return _c
}

// SetRequestJSON sets the "request_json" field.
func (_c *VideoTaskCreate) SetRequestJSON(v map[string]interface{}) *VideoTaskCreate {
	_c.mutation.SetRequestJSON(v)
	return _c
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (_c *VideoTaskCreate) SetUpstreamResponseJSON(v map[string]interface{}) *VideoTaskCreate {
	_c.mutation.SetUpstreamResponseJSON(v)
	return _c
}

// SetErrorJSON sets the "error_json" field.
func (_c *VideoTaskCreate) SetErrorJSON(v map[string]interface{}) *VideoTaskCreate {
	_c.mutation.SetErrorJSON(v)
	return _c
}

// SetResultVideoURL sets the "result_video_url" field.
func (_c *VideoTaskCreate) SetResultVideoURL(v string) *VideoTaskCreate {
	_c.mutation.SetResultVideoURL(v)
	return _c
}

// SetNillableResultVideoURL sets the "result_video_url" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableResultVideoURL(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetResultVideoURL(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoTaskCreate) SetCreatedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableCreatedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoTaskCreate) SetUpdatedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableUpdatedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *VideoTaskCreate) SetCompletedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableCompletedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetBilledAt sets the "billed_at" field.
func (_c *VideoTaskCreate) SetBilledAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetBilledAt(v)
	return _c
}

// SetNillableBilledAt sets the "billed_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableBilledAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetBilledAt(*v)
	}
	return _c
}

// SetRefundedAt sets the "refunded_at" field.
func (_c *VideoTaskCreate) SetRefundedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetRefundedAt(v)
	return _c
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableRefundedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetRefundedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *VideoTaskCreate) SetUser(v *User) *VideoTaskCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *VideoTaskCreate) SetAPIKey(v *APIKey) *VideoTaskCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *VideoTaskCreate) SetGroup(v *Group) *VideoTaskCreate {
	return _c.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *VideoTaskCreate) SetAccount(v *Account) *VideoTaskCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_c *VideoTaskCreate) Mutation() *VideoTaskMutation {
	return _c.mutation
}

// Save creates the VideoTask in the database.
func (_c *VideoTaskCreate) Save(ctx context.Context) (*VideoTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoTaskCreate) SaveX(ctx context.Context) *VideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoTaskCreate) defaults() {
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		v := videotask.DefaultDurationSeconds
		_c.mutation.SetDurationSeconds(v)
	}
	if _, ok := _c.mutation.ReferenceDurationSeconds(); !ok {
		v := videotask.DefaultReferenceDurationSeconds
		_c.mutation.SetReferenceDurationSeconds(v)
	}
	if _, ok := _c.mutation.BillableSeconds(); !ok {
		v := videotask.DefaultBillableSeconds
		_c.mutation.SetBillableSeconds(v)
	}
	if _, ok := _c.mutation.CostPerSecond(); !ok {
		v := videotask.DefaultCostPerSecond
		_c.mutation.SetCostPerSecond(v)
	}
	if _, ok := _c.mutation.TotalCost(); !ok {
		v := videotask.DefaultTotalCost
		_c.mutation.SetTotalCost(v)
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		v := videotask.DefaultActualCost
		_c.mutation.SetActualCost(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videotask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videotask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videotask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoTaskCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "VideoTask.public_id"`)}
	}
	if v, ok := _c.mutation.PublicID(); ok {
		if err := videotask.PublicIDValidator(v); err != nil {
			return &ValidationError{Name: "public_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.public_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := videotask.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VideoTask.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "VideoTask.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoTask.group_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "VideoTask.account_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "VideoTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := videotask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "VideoTask.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := videotask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Resolution(); !ok {
		return &ValidationError{Name: "resolution", err: errors.New(`ent: missing required field "VideoTask.resolution"`)}
	}
	if v, ok := _c.mutation.Resolution(); ok {
		if err := videotask.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoTask.resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "VideoTask.duration_seconds"`)}
	}
	if _, ok := _c.mutation.ReferenceDurationSeconds(); !ok {
		return &ValidationError{Name: "reference_duration_seconds", err: errors.New(`ent: missing required field "VideoTask.reference_duration_seconds"`)}
	}
	if _, ok := _c.mutation.BillableSeconds(); !ok {
		return &ValidationError{Name: "billable_seconds", err: errors.New(`ent: missing required field "VideoTask.billable_seconds"`)}
	}
	if _, ok := _c.mutation.CostPerSecond(); !ok {
		return &ValidationError{Name: "cost_per_second", err: errors.New(`ent: missing required field "VideoTask.cost_per_second"`)}
	}
	if _, ok := _c.mutation.TotalCost(); !ok {
		return &ValidationError{Name: "total_cost", err: errors.New(`ent: missing required field "VideoTask.total_cost"`)}
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		return &ValidationError{Name: "actual_cost", err: errors.New(`ent: missing required field "VideoTask.actual_cost"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoTask.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "VideoTask.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "VideoTask.api_key"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "VideoTask.group"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "VideoTask.account"`)}
	}
	return nil
}

func (_c *VideoTaskCreate) sqlSave(ctx context.Context) (*VideoTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoTaskCreate) createSpec() (*VideoTask, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videotask.Table, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(videotask.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(videotask.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(videotask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(videotask.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(videotask.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(videotask.FieldDurationSeconds, field.TypeInt, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.ReferenceDurationSeconds(); ok {
		_spec.SetField(videotask.FieldReferenceDurationSeconds, field.TypeInt, value)
		_node.ReferenceDurationSeconds = value
	}
	if value, ok := _c.mutation.BillableSeconds(); ok {
		_spec.SetField(videotask.FieldBillableSeconds, field.TypeInt, value)
		_node.BillableSeconds = value
	}
	if value, ok := _c.mutation.CostPerSecond(); ok {
		_spec.SetField(videotask.FieldCostPerSecond, field.TypeFloat64, value)
		_node.CostPerSecond = value
	}
	if value, ok := _c.mutation.TotalCost(); ok {
		_spec.SetField(videotask.FieldTotalCost, field.TypeFloat64, value)
		_node.TotalCost = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(videotask.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = &value
	}
	if value, ok := _c.mutation.RequestJSON(); ok {
		_spec.SetField(videotask.FieldRequestJSON, field.TypeJSON, value)
		_node.RequestJSON = value
	}
	if value, ok := _c.mutation.UpstreamResponseJSON(); ok {
		_spec.SetField(videotask.FieldUpstreamResponseJSON, field.TypeJSON, value)
		_node.UpstreamResponseJSON = value
	}
	if value, ok := _c.mutation.ErrorJSON(); ok {
		_spec.SetField(videotask.FieldErrorJSON, field.TypeJSON, value)
		_node.ErrorJSON = value
	}
	if value, ok := _c.mutation.ResultVideoURL(); ok {
		_spec.SetField(videotask.FieldResultVideoURL, field.TypeString, value)
		_node.ResultVideoURL = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videotask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(videotask.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.BilledAt(); ok {
		_spec.SetField(videotask.FieldBilledAt, field.TypeTime, value)
		_node.BilledAt = &value
	}
	if value, ok := _c.mutation.RefundedAt(); ok {
		_spec.SetField(videotask.FieldRefundedAt, field.TypeTime, value)
		_node.RefundedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.UserTable,
			Columns: []string{videotask.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.APIKeyTable,
			Columns: []string{videotask.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.GroupTable,
			Columns: []string{videotask.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   videotask.AccountTable,
			Columns: []string{videotask.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTask.Create().
//		SetPublicID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskUpsert) {
//			SetPublicID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskCreate) OnConflict(opts ...sql.ConflictOption) *VideoTaskUpsertOne {
	_c.conflict = opts
	return &VideoTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskCreate) OnConflictColumns(columns ...string) *VideoTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskUpsertOne{
		create: _c,
	}
}

type (
	// VideoTaskUpsertOne is the builder for "upsert"-ing
	//  one VideoTask node.
	VideoTaskUpsertOne struct {
		create *VideoTaskCreate
	}

	// VideoTaskUpsert is the "OnConflict" setter.
	VideoTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetPublicID sets the "public_id" field.
func (u *VideoTaskUpsert) SetPublicID(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldPublicID, v)
	return u
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdatePublicID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldPublicID)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *VideoTaskUpsert) SetRequestID(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateRequestID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *VideoTaskUpsert) ClearRequestID() *VideoTaskUpsert {
	u.SetNull(videotask.FieldRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *VideoTaskUpsert) SetUserID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUserID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *VideoTaskUpsert) SetAPIKeyID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateAPIKeyID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldAPIKeyID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *VideoTaskUpsert) SetGroupID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateGroupID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *VideoTaskUpsert) SetAccountID(v int64) *VideoTaskUpsert {
	u.Set(videotask.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateAccountID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldAccountID)
	return u
}

// SetModel sets the "model" field.
func (u *VideoTaskUpsert) SetModel(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateModel() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *VideoTaskUpsert) SetUpstreamModel(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpstreamModel() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpstreamModel)
	return u
}

// SetResolution sets the "resolution" field.
func (u *VideoTaskUpsert) SetResolution(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldResolution, v)
	return u
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateResolution() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldResolution)
	return u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VideoTaskUpsert) SetDurationSeconds(v int) *VideoTaskUpsert {
	u.Set(videotask.FieldDurationSeconds, v)
	return u
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateDurationSeconds() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldDurationSeconds)
	return u
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VideoTaskUpsert) AddDurationSeconds(v int) *VideoTaskUpsert {
	u.Add(videotask.FieldDurationSeconds, v)
	return u
}

// SetReferenceDurationSeconds sets the "reference_duration_seconds" field.
func (u *VideoTaskUpsert) SetReferenceDurationSeconds(v int) *VideoTaskUpsert {
	u.Set(videotask.FieldReferenceDurationSeconds, v)
	return u
}

// UpdateReferenceDurationSeconds sets the "reference_duration_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateReferenceDurationSeconds() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldReferenceDurationSeconds)
	return u
}

// AddReferenceDurationSeconds adds v to the "reference_duration_seconds" field.
func (u *VideoTaskUpsert) AddReferenceDurationSeconds(v int) *VideoTaskUpsert {
	u.Add(videotask.FieldReferenceDurationSeconds, v)
	return u
}

// SetBillableSeconds sets the "billable_seconds" field.
func (u *VideoTaskUpsert) SetBillableSeconds(v int) *VideoTaskUpsert {
	u.Set(videotask.FieldBillableSeconds, v)
	return u
}

// UpdateBillableSeconds sets the "billable_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateBillableSeconds() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldBillableSeconds)
	return u
}

// AddBillableSeconds adds v to the "billable_seconds" field.
func (u *VideoTaskUpsert) AddBillableSeconds(v int) *VideoTaskUpsert {
	u.Add(videotask.FieldBillableSeconds, v)
	return u
}

// SetCostPerSecond sets the "cost_per_second" field.
func (u *VideoTaskUpsert) SetCostPerSecond(v float64) *VideoTaskUpsert {
	u.Set(videotask.FieldCostPerSecond, v)
	return u
}

// UpdateCostPerSecond sets the "cost_per_second" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateCostPerSecond() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldCostPerSecond)
	return u
}

// AddCostPerSecond adds v to the "cost_per_second" field.
func (u *VideoTaskUpsert) AddCostPerSecond(v float64) *VideoTaskUpsert {
	u.Add(videotask.FieldCostPerSecond, v)
	return u
}

// SetTotalCost sets the "total_cost" field.
func (u *VideoTaskUpsert) SetTotalCost(v float64) *VideoTaskUpsert {
	u.Set(videotask.FieldTotalCost, v)
	return u
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateTotalCost() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldTotalCost)
	return u
}

// AddTotalCost adds v to the "total_cost" field.
func (u *VideoTaskUpsert) AddTotalCost(v float64) *VideoTaskUpsert {
	u.Add(videotask.FieldTotalCost, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *VideoTaskUpsert) SetActualCost(v float64) *VideoTaskUpsert {
	u.Set(videotask.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateActualCost() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *VideoTaskUpsert) AddActualCost(v float64) *VideoTaskUpsert {
	u.Add(videotask.FieldActualCost, v)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsert) SetStatus(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateStatus() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldStatus)
	return u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *VideoTaskUpsert) SetUpstreamTaskID(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldUpstreamTaskID, v)
	return u
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpstreamTaskID() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpstreamTaskID)
	return u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *VideoTaskUpsert) ClearUpstreamTaskID() *VideoTaskUpsert {
	u.SetNull(videotask.FieldUpstreamTaskID)
	return u
}

// SetRequestJSON sets the "request_json" field.
func (u *VideoTaskUpsert) SetRequestJSON(v map[string]interface{}) *VideoTaskUpsert {
	u.Set(videotask.FieldRequestJSON, v)
	return u
}

// UpdateRequestJSON sets the "request_json" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateRequestJSON() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldRequestJSON)
	return u
}

// ClearRequestJSON clears the value of the "request_json" field.
func (u *VideoTaskUpsert) ClearRequestJSON() *VideoTaskUpsert {
	u.SetNull(videotask.FieldRequestJSON)
	return u
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (u *VideoTaskUpsert) SetUpstreamResponseJSON(v map[string]interface{}) *VideoTaskUpsert {
	u.Set(videotask.FieldUpstreamResponseJSON, v)
	return u
}

// UpdateUpstreamResponseJSON sets the "upstream_response_json" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpstreamResponseJSON() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpstreamResponseJSON)
	return u
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (u *VideoTaskUpsert) ClearUpstreamResponseJSON() *VideoTaskUpsert {
	u.SetNull(videotask.FieldUpstreamResponseJSON)
	return u
}

// SetErrorJSON sets the "error_json" field.
func (u *VideoTaskUpsert) SetErrorJSON(v map[string]interface{}) *VideoTaskUpsert {
	u.Set(videotask.FieldErrorJSON, v)
	return u
}

// UpdateErrorJSON sets the "error_json" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateErrorJSON() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldErrorJSON)
	return u
}

// ClearErrorJSON clears the value of the "error_json" field.
func (u *VideoTaskUpsert) ClearErrorJSON() *VideoTaskUpsert {
	u.SetNull(videotask.FieldErrorJSON)
	return u
}

// SetResultVideoURL sets the "result_video_url" field.
func (u *VideoTaskUpsert) SetResultVideoURL(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldResultVideoURL, v)
	return u
}

// UpdateResultVideoURL sets the "result_video_url" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateResultVideoURL() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldResultVideoURL)
	return u
}

// ClearResultVideoURL clears the value of the "result_video_url" field.
func (u *VideoTaskUpsert) ClearResultVideoURL() *VideoTaskUpsert {
	u.SetNull(videotask.FieldResultVideoURL)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsert) SetUpdatedAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpdatedAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpdatedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *VideoTaskUpsert) SetCompletedAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateCompletedAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *VideoTaskUpsert) ClearCompletedAt() *VideoTaskUpsert {
	u.SetNull(videotask.FieldCompletedAt)
	return u
}

// SetBilledAt sets the "billed_at" field.
func (u *VideoTaskUpsert) SetBilledAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldBilledAt, v)
	return u
}

// UpdateBilledAt sets the "billed_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateBilledAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldBilledAt)
	return u
}

// ClearBilledAt clears the value of the "billed_at" field.
func (u *VideoTaskUpsert) ClearBilledAt() *VideoTaskUpsert {
	u.SetNull(videotask.FieldBilledAt)
	return u
}

// SetRefundedAt sets the "refunded_at" field.
func (u *VideoTaskUpsert) SetRefundedAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldRefundedAt, v)
	return u
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateRefundedAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldRefundedAt)
	return u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *VideoTaskUpsert) ClearRefundedAt() *VideoTaskUpsert {
	u.SetNull(videotask.FieldRefundedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskUpsertOne) UpdateNewValues() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videotask.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoTaskUpsertOne) Ignore() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskUpsertOne) DoNothing() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskCreate.OnConflict
// documentation for more info.
func (u *VideoTaskUpsertOne) Update(set func(*VideoTaskUpsert)) *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublicID sets the "public_id" field.
func (u *VideoTaskUpsertOne) SetPublicID(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdatePublicID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdatePublicID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *VideoTaskUpsertOne) SetRequestID(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateRequestID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *VideoTaskUpsertOne) ClearRequestID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *VideoTaskUpsertOne) SetUserID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUserID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *VideoTaskUpsertOne) SetAPIKeyID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateAPIKeyID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *VideoTaskUpsertOne) SetGroupID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateGroupID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *VideoTaskUpsertOne) SetAccountID(v int64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateAccountID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetModel sets the "model" field.
func (u *VideoTaskUpsertOne) SetModel(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateModel() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *VideoTaskUpsertOne) SetUpstreamModel(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpstreamModel() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetResolution sets the "resolution" field.
func (u *VideoTaskUpsertOne) SetResolution(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateResolution() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateResolution()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VideoTaskUpsertOne) SetDurationSeconds(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VideoTaskUpsertOne) AddDurationSeconds(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateDurationSeconds() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateDurationSeconds()
	})
}

// SetReferenceDurationSeconds sets the "reference_duration_seconds" field.
func (u *VideoTaskUpsertOne) SetReferenceDurationSeconds(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetReferenceDurationSeconds(v)
	})
}

// AddReferenceDurationSeconds adds v to the "reference_duration_seconds" field.
func (u *VideoTaskUpsertOne) AddReferenceDurationSeconds(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddReferenceDurationSeconds(v)
	})
}

// UpdateReferenceDurationSeconds sets the "reference_duration_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateReferenceDurationSeconds() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateReferenceDurationSeconds()
	})
}

// SetBillableSeconds sets the "billable_seconds" field.
func (u *VideoTaskUpsertOne) SetBillableSeconds(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetBillableSeconds(v)
	})
}

// AddBillableSeconds adds v to the "billable_seconds" field.
func (u *VideoTaskUpsertOne) AddBillableSeconds(v int) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddBillableSeconds(v)
	})
}

// UpdateBillableSeconds sets the "billable_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateBillableSeconds() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateBillableSeconds()
	})
}

// SetCostPerSecond sets the "cost_per_second" field.
func (u *VideoTaskUpsertOne) SetCostPerSecond(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetCostPerSecond(v)
	})
}

// AddCostPerSecond adds v to the "cost_per_second" field.
func (u *VideoTaskUpsertOne) AddCostPerSecond(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddCostPerSecond(v)
	})
}

// UpdateCostPerSecond sets the "cost_per_second" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateCostPerSecond() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateCostPerSecond()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *VideoTaskUpsertOne) SetTotalCost(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *VideoTaskUpsertOne) AddTotalCost(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateTotalCost() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateTotalCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *VideoTaskUpsertOne) SetActualCost(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *VideoTaskUpsertOne) AddActualCost(v float64) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateActualCost() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateActualCost()
	})
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsertOne) SetStatus(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateStatus() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *VideoTaskUpsertOne) SetUpstreamTaskID(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpstreamTaskID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *VideoTaskUpsertOne) ClearUpstreamTaskID() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetRequestJSON sets the "request_json" field.
func (u *VideoTaskUpsertOne) SetRequestJSON(v map[string]interface{}) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRequestJSON(v)
	})
}

// UpdateRequestJSON sets the "request_json" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateRequestJSON() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRequestJSON()
	})
}

// ClearRequestJSON clears the value of the "request_json" field.
func (u *VideoTaskUpsertOne) ClearRequestJSON() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRequestJSON()
	})
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (u *VideoTaskUpsertOne) SetUpstreamResponseJSON(v map[string]interface{}) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamResponseJSON(v)
	})
}

// UpdateUpstreamResponseJSON sets the "upstream_response_json" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpstreamResponseJSON() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamResponseJSON()
	})
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (u *VideoTaskUpsertOne) ClearUpstreamResponseJSON() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearUpstreamResponseJSON()
	})
}

// SetErrorJSON sets the "error_json" field.
func (u *VideoTaskUpsertOne) SetErrorJSON(v map[string]interface{}) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetErrorJSON(v)
	})
}

// UpdateErrorJSON sets the "error_json" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateErrorJSON() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateErrorJSON()
	})
}

// ClearErrorJSON clears the value of the "error_json" field.
func (u *VideoTaskUpsertOne) ClearErrorJSON() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearErrorJSON()
	})
}

// SetResultVideoURL sets the "result_video_url" field.
func (u *VideoTaskUpsertOne) SetResultVideoURL(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetResultVideoURL(v)
	})
}

// UpdateResultVideoURL sets the "result_video_url" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateResultVideoURL() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateResultVideoURL()
	})
}

// ClearResultVideoURL clears the value of the "result_video_url" field.
func (u *VideoTaskUpsertOne) ClearResultVideoURL() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearResultVideoURL()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsertOne) SetUpdatedAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpdatedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *VideoTaskUpsertOne) SetCompletedAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateCompletedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *VideoTaskUpsertOne) ClearCompletedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearCompletedAt()
	})
}

// SetBilledAt sets the "billed_at" field.
func (u *VideoTaskUpsertOne) SetBilledAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetBilledAt(v)
	})
}

// UpdateBilledAt sets the "billed_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateBilledAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateBilledAt()
	})
}

// ClearBilledAt clears the value of the "billed_at" field.
func (u *VideoTaskUpsertOne) ClearBilledAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearBilledAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *VideoTaskUpsertOne) SetRefundedAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateRefundedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *VideoTaskUpsertOne) ClearRefundedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRefundedAt()
	})
}

// Exec executes the query.
func (u *VideoTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoTaskCreateBulk is the builder for creating many VideoTask entities in bulk.
type VideoTaskCreateBulk struct {
	config
	err      error
	builders []*VideoTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoTask entities in the database.
func (_c *VideoTaskCreateBulk) Save(ctx context.Context) ([]*VideoTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoTaskCreateBulk) SaveX(ctx context.Context) []*VideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskUpsert) {
//			SetPublicID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoTaskUpsertBulk {
	_c.conflict = opts
	return &VideoTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskCreateBulk) OnConflictColumns(columns ...string) *VideoTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskUpsertBulk{
		create: _c,
	}
}

// VideoTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoTask nodes.
type VideoTaskUpsertBulk struct {
	create *VideoTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskUpsertBulk) UpdateNewValues() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videotask.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoTaskUpsertBulk) Ignore() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskUpsertBulk) DoNothing() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskCreateBulk.OnConflict
// documentation for more info.
func (u *VideoTaskUpsertBulk) Update(set func(*VideoTaskUpsert)) *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetPublicID sets the "public_id" field.
func (u *VideoTaskUpsertBulk) SetPublicID(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetPublicID(v)
	})
}

// UpdatePublicID sets the "public_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdatePublicID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdatePublicID()
	})
}

// SetRequestID sets the "request_id" field.
func (u *VideoTaskUpsertBulk) SetRequestID(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateRequestID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *VideoTaskUpsertBulk) ClearRequestID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *VideoTaskUpsertBulk) SetUserID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUserID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *VideoTaskUpsertBulk) SetAPIKeyID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateAPIKeyID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *VideoTaskUpsertBulk) SetGroupID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateGroupID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *VideoTaskUpsertBulk) SetAccountID(v int64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateAccountID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateAccountID()
	})
}

// SetModel sets the "model" field.
func (u *VideoTaskUpsertBulk) SetModel(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateModel() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *VideoTaskUpsertBulk) SetUpstreamModel(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpstreamModel() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetResolution sets the "resolution" field.
func (u *VideoTaskUpsertBulk) SetResolution(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetResolution(v)
	})
}

// UpdateResolution sets the "resolution" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateResolution() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateResolution()
	})
}

// SetDurationSeconds sets the "duration_seconds" field.
func (u *VideoTaskUpsertBulk) SetDurationSeconds(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetDurationSeconds(v)
	})
}

// AddDurationSeconds adds v to the "duration_seconds" field.
func (u *VideoTaskUpsertBulk) AddDurationSeconds(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddDurationSeconds(v)
	})
}

// UpdateDurationSeconds sets the "duration_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateDurationSeconds() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateDurationSeconds()
	})
}

// SetReferenceDurationSeconds sets the "reference_duration_seconds" field.
func (u *VideoTaskUpsertBulk) SetReferenceDurationSeconds(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetReferenceDurationSeconds(v)
	})
}

// AddReferenceDurationSeconds adds v to the "reference_duration_seconds" field.
func (u *VideoTaskUpsertBulk) AddReferenceDurationSeconds(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddReferenceDurationSeconds(v)
	})
}

// UpdateReferenceDurationSeconds sets the "reference_duration_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateReferenceDurationSeconds() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateReferenceDurationSeconds()
	})
}

// SetBillableSeconds sets the "billable_seconds" field.
func (u *VideoTaskUpsertBulk) SetBillableSeconds(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetBillableSeconds(v)
	})
}

// AddBillableSeconds adds v to the "billable_seconds" field.
func (u *VideoTaskUpsertBulk) AddBillableSeconds(v int) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddBillableSeconds(v)
	})
}

// UpdateBillableSeconds sets the "billable_seconds" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateBillableSeconds() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateBillableSeconds()
	})
}

// SetCostPerSecond sets the "cost_per_second" field.
func (u *VideoTaskUpsertBulk) SetCostPerSecond(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetCostPerSecond(v)
	})
}

// AddCostPerSecond adds v to the "cost_per_second" field.
func (u *VideoTaskUpsertBulk) AddCostPerSecond(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddCostPerSecond(v)
	})
}

// UpdateCostPerSecond sets the "cost_per_second" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateCostPerSecond() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateCostPerSecond()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *VideoTaskUpsertBulk) SetTotalCost(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *VideoTaskUpsertBulk) AddTotalCost(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateTotalCost() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateTotalCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *VideoTaskUpsertBulk) SetActualCost(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *VideoTaskUpsertBulk) AddActualCost(v float64) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateActualCost() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateActualCost()
	})
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsertBulk) SetStatus(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateStatus() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (u *VideoTaskUpsertBulk) SetUpstreamTaskID(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamTaskID(v)
	})
}

// UpdateUpstreamTaskID sets the "upstream_task_id" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpstreamTaskID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamTaskID()
	})
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (u *VideoTaskUpsertBulk) ClearUpstreamTaskID() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearUpstreamTaskID()
	})
}

// SetRequestJSON sets the "request_json" field.
func (u *VideoTaskUpsertBulk) SetRequestJSON(v map[string]interface{}) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRequestJSON(v)
	})
}

// UpdateRequestJSON sets the "request_json" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateRequestJSON() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRequestJSON()
	})
}

// ClearRequestJSON clears the value of the "request_json" field.
func (u *VideoTaskUpsertBulk) ClearRequestJSON() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRequestJSON()
	})
}

// SetUpstreamResponseJSON sets the "upstream_response_json" field.
func (u *VideoTaskUpsertBulk) SetUpstreamResponseJSON(v map[string]interface{}) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpstreamResponseJSON(v)
	})
}

// UpdateUpstreamResponseJSON sets the "upstream_response_json" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpstreamResponseJSON() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpstreamResponseJSON()
	})
}

// ClearUpstreamResponseJSON clears the value of the "upstream_response_json" field.
func (u *VideoTaskUpsertBulk) ClearUpstreamResponseJSON() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearUpstreamResponseJSON()
	})
}

// SetErrorJSON sets the "error_json" field.
func (u *VideoTaskUpsertBulk) SetErrorJSON(v map[string]interface{}) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetErrorJSON(v)
	})
}

// UpdateErrorJSON sets the "error_json" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateErrorJSON() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateErrorJSON()
	})
}

// ClearErrorJSON clears the value of the "error_json" field.
func (u *VideoTaskUpsertBulk) ClearErrorJSON() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearErrorJSON()
	})
}

// SetResultVideoURL sets the "result_video_url" field.
func (u *VideoTaskUpsertBulk) SetResultVideoURL(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetResultVideoURL(v)
	})
}

// UpdateResultVideoURL sets the "result_video_url" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateResultVideoURL() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateResultVideoURL()
	})
}

// ClearResultVideoURL clears the value of the "result_video_url" field.
func (u *VideoTaskUpsertBulk) ClearResultVideoURL() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearResultVideoURL()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsertBulk) SetUpdatedAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpdatedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *VideoTaskUpsertBulk) SetCompletedAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateCompletedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *VideoTaskUpsertBulk) ClearCompletedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearCompletedAt()
	})
}

// SetBilledAt sets the "billed_at" field.
func (u *VideoTaskUpsertBulk) SetBilledAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetBilledAt(v)
	})
}

// UpdateBilledAt sets the "billed_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateBilledAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateBilledAt()
	})
}

// ClearBilledAt clears the value of the "billed_at" field.
func (u *VideoTaskUpsertBulk) ClearBilledAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearBilledAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *VideoTaskUpsertBulk) SetRefundedAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateRefundedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *VideoTaskUpsertBulk) ClearRefundedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.ClearRefundedAt()
	})
}

// Exec executes the query.
func (u *VideoTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
