// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videogrouppricingrule"
)

// VideoGroupPricingRuleDelete is the builder for deleting a VideoGroupPricingRule entity.
type VideoGroupPricingRuleDelete struct {
	config
	hooks    []Hook
	mutation *VideoGroupPricingRuleMutation
}

// Where appends a list predicates to the VideoGroupPricingRuleDelete builder.
func (_d *VideoGroupPricingRuleDelete) Where(ps ...predicate.VideoGroupPricingRule) *VideoGroupPricingRuleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *VideoGroupPricingRuleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VideoGroupPricingRuleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *VideoGroupPricingRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(videogrouppricingrule.Table, sqlgraph.NewFieldSpec(videogrouppricingrule.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// VideoGroupPricingRuleDeleteOne is the builder for deleting a single VideoGroupPricingRule entity.
type VideoGroupPricingRuleDeleteOne struct {
	_d *VideoGroupPricingRuleDelete
}

// Where appends a list predicates to the VideoGroupPricingRuleDelete builder.
func (_d *VideoGroupPricingRuleDeleteOne) Where(ps ...predicate.VideoGroupPricingRule) *VideoGroupPricingRuleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *VideoGroupPricingRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{videogrouppricingrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *VideoGroupPricingRuleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
