#!/usr/bin/env bash
# Build a standalone ffprobe and generate the platform-specific Go embed file.
# Native builds only; Linux uses musl so the result also works in old containers.
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
target_os=${1:?usage: build-ffprobe.sh GOOS GOARCH}
target_arch=${2:?usage: build-ffprobe.sh GOOS GOARCH}
version=8.1.3
source_sha256=7138d28c96d9d3e3af4ee3d8cad72741f8ffb40da90c1112235dea3ecd3178a3
output="$repo_root/backend/internal/pkg/mediaprobe"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

sha256() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | cut -d ' ' -f 1
    else
        shasum -a 256 "$1" | cut -d ' ' -f 1
    fi
}

archive="ffmpeg-$version.tar.xz"
curl --fail --location --retry 3 --max-time 180 \
    "https://ffmpeg.org/releases/$archive" -o "$work/$archive"
test "$(sha256 "$work/$archive")" = "$source_sha256" || {
    echo 'FFmpeg source checksum mismatch' >&2
    exit 1
}
tar -xf "$work/$archive" -C "$work"
cd "$work/ffmpeg-$version"

flags=(--disable-autodetect --disable-network --disable-doc --disable-debug
    --disable-programs --enable-ffprobe --disable-shared --enable-static
    --disable-avdevice --disable-avfilter --disable-encoders --disable-muxers
    --disable-bsfs --disable-hwaccels --disable-asm
    --disable-protocols --enable-protocol=file)
case "$target_os/$target_arch" in
    linux/amd64|linux/arm64)
        flags+=(--extra-ldflags=-static)
        ;;
    darwin/amd64|darwin/arm64)
        export MACOSX_DEPLOYMENT_TARGET=12.0
        ;;
    windows/amd64)
        flags+=(--target-os=mingw32 --arch=x86_64 --extra-ldflags=-static)
        ;;
    *) echo "Unsupported ffprobe target: $target_os/$target_arch" >&2; exit 1 ;;
esac
./configure "${flags[@]}"
probe=ffprobe
if [ "$target_os" = windows ]; then probe=ffprobe.exe; fi
make -j "${FFPROBE_BUILD_JOBS:-4}" "$probe"
if [ "$target_os" = darwin ]; then codesign --force --sign - "$probe"; fi
./"$probe" -version
if [ "$target_os" = linux ]; then
    # Fail before publication if an unintended dynamic dependency slipped in.
    if readelf -l "$probe" | grep -q INTERP; then
        echo 'Bundled Linux ffprobe must be statically linked' >&2
        exit 1
    fi
fi
digest=$(sha256 "$probe")
mkdir -p "$output"
gzip -n -9 -c "$probe" > "$output/ffprobe_${target_os}_${target_arch}.gz"
cat > "$output/payload_${target_os}_${target_arch}.go" <<EOF
// Code generated by deploy/build-ffprobe.sh; DO NOT EDIT.
//go:build bundled_ffprobe

package mediaprobe

import _ "embed"

//go:embed ffprobe_${target_os}_${target_arch}.gz
var bundledGZIP []byte

const bundledSHA256 = "$digest"
EOF

# Distribute the exact unmodified source and license with the release.
if [ "$target_os/$target_arch" = linux/amd64 ]; then
    mkdir -p "$repo_root/dist/ffprobe-source"
    cp "$work/$archive" COPYING.LGPLv2.1 "$repo_root/dist/ffprobe-source/"
fi
