// Code generated by ent, DO NOT EDIT.

package videogrouppricingrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldGroupID, v))
}

// ModelCode applies equality check predicate on the "model_code" field. It's identical to ModelCodeEQ.
func ModelCode(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldModelCode, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldResolution, v))
}

// CreditsPerSecond applies equality check predicate on the "credits_per_second" field. It's identical to CreditsPerSecondEQ.
func CreditsPerSecond(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldCreditsPerSecond, v))
}

// ReferenceVideoMultiplier applies equality check predicate on the "reference_video_multiplier" field. It's identical to ReferenceVideoMultiplierEQ.
func ReferenceVideoMultiplier(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldReferenceVideoMultiplier, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldGroupID, vs...))
}

// ModelCodeEQ applies the EQ predicate on the "model_code" field.
func ModelCodeEQ(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldModelCode, v))
}

// ModelCodeNEQ applies the NEQ predicate on the "model_code" field.
func ModelCodeNEQ(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldModelCode, v))
}

// ModelCodeIn applies the In predicate on the "model_code" field.
func ModelCodeIn(vs ...string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldModelCode, vs...))
}

// ModelCodeNotIn applies the NotIn predicate on the "model_code" field.
func ModelCodeNotIn(vs ...string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldModelCode, vs...))
}

// ModelCodeGT applies the GT predicate on the "model_code" field.
func ModelCodeGT(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldModelCode, v))
}

// ModelCodeGTE applies the GTE predicate on the "model_code" field.
func ModelCodeGTE(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldModelCode, v))
}

// ModelCodeLT applies the LT predicate on the "model_code" field.
func ModelCodeLT(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldModelCode, v))
}

// ModelCodeLTE applies the LTE predicate on the "model_code" field.
func ModelCodeLTE(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldModelCode, v))
}

// ModelCodeContains applies the Contains predicate on the "model_code" field.
func ModelCodeContains(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldContains(FieldModelCode, v))
}

// ModelCodeHasPrefix applies the HasPrefix predicate on the "model_code" field.
func ModelCodeHasPrefix(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldHasPrefix(FieldModelCode, v))
}

// ModelCodeHasSuffix applies the HasSuffix predicate on the "model_code" field.
func ModelCodeHasSuffix(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldHasSuffix(FieldModelCode, v))
}

// ModelCodeEqualFold applies the EqualFold predicate on the "model_code" field.
func ModelCodeEqualFold(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEqualFold(FieldModelCode, v))
}

// ModelCodeContainsFold applies the ContainsFold predicate on the "model_code" field.
func ModelCodeContainsFold(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldContainsFold(FieldModelCode, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldContainsFold(FieldResolution, v))
}

// CreditsPerSecondEQ applies the EQ predicate on the "credits_per_second" field.
func CreditsPerSecondEQ(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldCreditsPerSecond, v))
}

// CreditsPerSecondNEQ applies the NEQ predicate on the "credits_per_second" field.
func CreditsPerSecondNEQ(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldCreditsPerSecond, v))
}

// CreditsPerSecondIn applies the In predicate on the "credits_per_second" field.
func CreditsPerSecondIn(vs ...float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldCreditsPerSecond, vs...))
}

// CreditsPerSecondNotIn applies the NotIn predicate on the "credits_per_second" field.
func CreditsPerSecondNotIn(vs ...float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldCreditsPerSecond, vs...))
}

// CreditsPerSecondGT applies the GT predicate on the "credits_per_second" field.
func CreditsPerSecondGT(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldCreditsPerSecond, v))
}

// CreditsPerSecondGTE applies the GTE predicate on the "credits_per_second" field.
func CreditsPerSecondGTE(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldCreditsPerSecond, v))
}

// CreditsPerSecondLT applies the LT predicate on the "credits_per_second" field.
func CreditsPerSecondLT(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldCreditsPerSecond, v))
}

// CreditsPerSecondLTE applies the LTE predicate on the "credits_per_second" field.
func CreditsPerSecondLTE(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldCreditsPerSecond, v))
}

// ReferenceVideoMultiplierEQ applies the EQ predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierEQ(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldReferenceVideoMultiplier, v))
}

// ReferenceVideoMultiplierNEQ applies the NEQ predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierNEQ(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldReferenceVideoMultiplier, v))
}

// ReferenceVideoMultiplierIn applies the In predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierIn(vs ...float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldReferenceVideoMultiplier, vs...))
}

// ReferenceVideoMultiplierNotIn applies the NotIn predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierNotIn(vs ...float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldReferenceVideoMultiplier, vs...))
}

// ReferenceVideoMultiplierGT applies the GT predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierGT(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldReferenceVideoMultiplier, v))
}

// ReferenceVideoMultiplierGTE applies the GTE predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierGTE(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldReferenceVideoMultiplier, v))
}

// ReferenceVideoMultiplierLT applies the LT predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierLT(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldReferenceVideoMultiplier, v))
}

// ReferenceVideoMultiplierLTE applies the LTE predicate on the "reference_video_multiplier" field.
func ReferenceVideoMultiplierLTE(v float64) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldReferenceVideoMultiplier, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoGroupPricingRule) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoGroupPricingRule) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoGroupPricingRule) predicate.VideoGroupPricingRule {
	return predicate.VideoGroupPricingRule(sql.NotPredicates(p))
}
